//!!NODE_ROOT <section>
include::../../includes.txt[]
:java-oracle-completablefuture: https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/CompletableFuture.html
[."topic"]
[[asynchronous,asynchronous.title]]
= Asynchronous programming
:info_doctype: section
:info_title: Asynchronous programming in the {sdkjavav2}
:info_titleabbrev: Asynchronous APIs
:info_abstract: How asynchronous programming works in the {sdkjavav2}

[abstract]
--
How asynchronous programming works in the {sdkjavav2}
--

The {sdkjavav2} features truly nonblocking asynchronous clients that implement high concurrency
across a few threads. The {sdk-java} 1.x has asynchronous clients that are wrappers around a
thread pool and blocking synchronous clients that don't provide the full benefit of nonblocking
I/O.

Synchronous methods block your thread's execution until the client receives a response from the
service. Asynchronous methods return immediately, giving control back to the calling thread
without waiting for a response.

Because an asynchronous method returns before a response is available, you need a way to get the
response when it's ready. The methods for asynchronous client in {v2ver} of the {sdk-java} return
_CompletableFuture objects_ that allow you to access the response when it's ready.

[[basics-async-non-streaming,basics-async-non-streaming.title]]
== Non-streaming operations

For non-streaming operations, asynchronous method calls are similar to synchronous methods.
However, the asynchronous methods in the {sdk-java} return a
{java-oracle-completablefuture}[CompletableFuture]
object that contains the results of the asynchronous operation __in the future__.

Call the `CompletableFuture` `whenComplete()` method with an action to complete when the result
is available. `CompletableFuture` implements the `Future` interface, so you can also get the
response object by calling the `get()` method.

The following is an example of an asynchronous operation that calls a {DDBlong} function to
get a list of tables, receiving a `CompletableFuture` that can hold a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ListTablesResponse.html[ListTablesResponse]
object. The action defined in the call to `whenComplete()` is done only when the asynchronous
call is complete.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.dbasync.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.dbasync.main.txt[]
----

The following code example shows you how to retrieve an Item from a table by using the
Asynchronous client. Invoke the `getItem` method of the DynamoDbAsyncClient and pass it a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/GetItemRequest.html[GetItemRequest]
object with the table name and primary key value of the item you want. This is typically how you
pass data that the operation requires. In this example, notice that a String value is passed.

*Imports*

[source,java]
----
include::../../snippets/dynamoasyn.java2.get_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamoasyc.java2.get_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodbasync/src/main/java/com/example/dynamodbasync/DynamoDBAsyncGetItem.java[complete example]
on GitHub.

[[basics-async-streaming,basics-async-streaming.title]]
== Streaming operations

For streaming operations, you must provide an
{v2javadocs}software/amazon/awssdk/core/async/AsyncRequestBody.html[AsyncRequestBody]
to provide the content incrementally, or an
{v2javadocs}software/amazon/awssdk/core/async/AsyncResponseTransformer.html[AsyncResponseTransformer]
to receive and process the response.

The following example uploads a file to {S3} asynchronously by using the `PutObject` operation.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.async_ops.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/s3.java2.async_ops.main.txt[]
----

The following example gets a file from {S3} asynchronously by using the `GetObject` operation.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.async_stream_ops.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/s3.java2.async_stream_ops.main.txt[]
----


[[advanced-operations,advanced-operations.title]]
== Advanced operations

The {sdkjavav2} uses https://netty.io[Netty], an asynchronous event-driven network
application framework, to handle I/O threads. The {sdkjavav2} creates an
`ExecutorService` behind Netty, to complete the futures returned from the HTTP client request
through to the Netty client. This abstraction reduces the risk of an application breaking the
async process if developers choose to stop or sleep threads. By default, 50 Threads are generated
for each asynchronous client, and managed in a queue within the ``ExecutorService``.

Advanced users can specify their thread pool size when creating an asynchronous client using the
following option when building.

*Code*

[source,java]
----
S3AsyncClient clientThread = S3AsyncClient.builder()
  .asyncConfiguration(
    b -> b.advancedOption(SdkAdvancedAsyncClientOption
      .FUTURE_COMPLETION_EXECUTOR,
      Executors.newFixedThreadPool(10)
    )
  )
  .build();
----

To optimize performance, you can manage your own thread pool executor, and include it when
configuring your client.

[source,java]
----
ThreadPoolExecutor executor = new ThreadPoolExecutor(50, 50,
    10, TimeUnit.SECONDS,
    new LinkedBlockingQueue<>(10_000),
    new ThreadFactoryBuilder()
      .threadNamePrefix("sdk-async-response").build());

// Allow idle core threads to time out
executor.allowCoreThreadTimeOut(true);

S3AsyncClient clientThread = S3AsyncClient.builder()
  .asyncConfiguration(
    b -> b.advancedOption(SdkAdvancedAsyncClientOption
      .FUTURE_COMPLETION_EXECUTOR,
      executor
    )
  )
  .build();
----

If you prefer to not use a thread pool, at all, use _Runnable::run_ instead of using a thread
pool executor.

[source,java]
----
S3AsyncClient clientThread = S3AsyncClient.builder() 
  .asyncConfiguration(
    b -> b.advancedOption(SdkAdvancedAsyncClientOption
        .FUTURE_COMPLETION_EXECUTOR,
        Runnable::run
      )
    )
    .build();
----
