//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[credentials,credentials.title]]
= [[using-credentials, Using credentials]]Using credentials
:info_doctype: section
:info_title: Using credentials
:info_abstract: Use {AWS} credentials with the {sdkjavav2}.
:info_keywordset: credentials, authorization, configuration, password, authentication, \
   authenticate, javasdkaws, DefaultCredentials, Providerchain, provider

[abstract]
--
Use {AWS} credentials with the {sdkjavav2}.
--

To make requests to {AWSlong} using the {sdk-java}, you must use cryptographically-signed
credentials issued by {AWS}. You can use programmatic access keys or temporary security credentials
such {SSO} or {IAM} roles to grant access to {AWS} resources.

For information on setting up credentials, see
xref:setup-credentials[Set default credentials and Region,linkend=setup-credentials] and
xref:setup-additional-credentials[Set up credentials profiles,linkend=setup-additional-credentials].

[.topiclist-abbrev]
[[Topic List]]

[[credentials-chain,credentials-chain.title]]
== Use the default credential provider chain

After you xref:setup-credentials[Set default credentials and Region,linkend=setup-credentials]
for your environment, the {sdk-java} will automatically use those credentials when your application
makes requests to {AWS}. The default credential provider chain, implemented by the
{v2javadocs}software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html[DefaultCredentialsProvider]
class, checks sequentially each of places where you can set default credentials and selects the
first one you set.

To use the default credential provider chain to supply credentials in your application, create a
service client builder without specifying credentials provider configuration.

[source,java]
----
Region region = Region.US_WEST_2;
DynamoDbClient ddb = DynamoDbClient.builder()
      .region(region)
      .build();
----

[[credentials-default,credentials-default.title]]
=== Credential retrieval order

The default credential provider chain of the {sdkjavav2} searches for credentials in your
environment using a predefined sequence.

. Java system properties
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/SystemPropertyCredentialsProvider.html[SystemPropertyCredentialsProvider]
class to load credentials from the `aws.accessKeyId` and `aws.secretAccessKey` Java system properties.
If `aws.sessionToken` is also specified, the SDK will use temporary credentials.
+
NOTE: For information on how to set Java system properties, see the
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html[System Properties]
tutorial on the official _Java Tutorials_ website.
. Environment variables
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/EnvironmentVariableCredentialsProvider.html[EnvironmentVariableCredentialsProvider]
class to load credentials from the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` system
environment variables. If `AWS_SESSION_TOKEN` is also specified, the SDK will use temporary
credentials.
. Web identity token from {STS}
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.html[WebIdentityTokenFileCredentialsProvider]
class to load credentials from Java system properties or environment variables.
. The shared [path]``credentials`` and [path]``config`` files
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.html[ProfileCredentialsProvider]
to load credentials from the `[default]` credentials profile in the shared [path]``credentials``
and [path]``config`` files.
+
NOTE: The [path]``credentials`` and [path]``config`` files are shared by various {AWS} SDKs and
Tools. For more information, see
link:sdkref/latest/guide/creds-config-files.html["The .aws/credentials and .aws/config files", type="documentation"]
in the link:sdkref/latest/guide["pass:q[[.shared\]`AWS`] SDKs and Tools Reference Guide", type="documentation"].
. {ECS} container credentials
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.html[ContainerCredentialsProvider]
class to load credentials from the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` system environment
variable.
. {EC2} instance profile credentials
+
** The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.html[InstanceProfileCredentialsProvider]
class to load credentials from the {EC2} metadata service.


[[credentials-specify,credentials-specify.title]]
== Use a specific credentials provider or provider chain

Alternatively, you can specify which credentials provider the SDK should use. For example, if you
set your default credentials using environment variables, supply an
{v2javadocs}software/amazon/awssdk/auth/credentials/EnvironmentVariableCredentialsProvider.html[EnvironmentVariableCredentialsProvider]
object to the `credentialsProvider` method on the service client builder, as in the following
code snippet.

[source,java]
----
Region region = Region.US_WEST_2;
DynamoDbClient ddb = DynamoDbClient.builder()
      .region(region)
      .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
      .build();
----

For a complete list of credential providers and provider chains, see *All Known Implementing
Classes* in {v2javadocs}software/amazon/awssdk/auth/credentials/AwsCredentialsProvider.html[AwsCredentialsProvider].

[NOTE]
====

You can use your own credential provider or provider chains by implementing the
`AwsCredentialsProvider` interface.

====

[[credentials-profiles,credentials-profiles.title]]
== Use credentials profiles

Using the shared [path]``credentials`` file, you can set up custom profiles which enables you to
use multiple sets of credentials in your application. The `[default]` profile was mentioned above.
The SDK uses the
{v2javadocs}software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.html[ProfileCredentialsProvider]
class to load credentials from profiles defined in the shared [path]``credentials`` file.

For information on how to set up custom profiles, see xref:setup-additional-credentials[Set up credentials profiles,linkend=setup-additional-credentials].

This code snippet demonstrates how to build a service client that uses the credentials defined as
part of the `profile_name` profile.

[source,java]
----
Region region = Region.US_WEST_2;
DynamoDbClient ddb = DynamoDbClient.builder()
      .region(region)
      .credentialsProvider(ProfileCredentialsProvider.create("profile_name"))
      .build();
----


[[set-a-custom-profile-as-the-default,set-a-custom-profile-as-the-default.title]]
=== Set a custom profile as the default

To set a profile other than the `[default]` profile as the default for your application, set the
`AWS_PROFILE` environment variable to the name of your custom profile.

To set this variable on Linux, macOS, or Unix, use ``export``:

[source,sh]
----
export AWS_PROFILE="other_profile"
----

To set these variables on Windows, use ``set``:

[source,sh]
----
set AWS_PROFILE="other_profile"
----

Alternatively, set the `aws.profile` Java system property to the name of the profile.

[[credentials-explicit,credentials-explicit.title]]
== Supply credentials explicitly

If the default credential chain or a specific or custom provider or provider chain doesn't work
for your application, you can supply the credentials that you want directly in code. These can be
{AWS-account} credentials, {IAM} credentials, or temporary credentials retrieved from {STSlong}
({STS}). If you've retrieved temporary credentials using {STS}, use this
method to specify the credentials for {AWS} access.

[IMPORTANT]
====

For security, use _{IAM} account credentials_ instead of the {AWS-account} credentials when
accessing {AWS}. For more information, see
link:general/latest/gr/aws-security-credentials.html["pass:q[[.shared\]`AWS`] Security Credentials", type="documentation"]
in the {AWS-GEN-REF-long}.

====
. Instantiate a class that provides the
{v2javadocs}software/amazon/awssdk/auth/credentials/AwsCredentials.html[AwsCredentials]
interface, such as
{v2javadocs}software/amazon/awssdk/auth/credentials/AwsSessionCredentials.html[AwsSessionCredentials].
Supply it with the {AWS} access key and secret key to use for the connection.
. Create a
{v2javadocs}software/amazon/awssdk/auth/credentials/StaticCredentialsProvider.html[StaticCredentialsProvider]
object and supply it with the `AwsCredentials` object.
. Configure the service client builder with the `StaticCredentialsProvider` and build the client.

The following example creates a new service client using credentials that you supply:

[source,java]
----
AwsBasicCredentials awsCreds = AwsBasicCredentials.create(
  "your_access_key_id",
  "your_secret_access_key");

S3Client s3 = S3Client.builder()
            .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
            .build();
----

include::ec2-iam-roles.adoc[leveloffset=+1]
