//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[dynamodb-enhanced-client,dynamodb-enhanced-client.title]]
= [[using-dynamodb-enhanced-client, Using the DynamoDB Enhanced Client]]Using the {DDB} Enhanced Client in the {sdkjavav2}
:info_doctype: section
:info_title: Using the {DDB} Enhanced Client in the {sdkjavav2}
:info_titleabbrev: {DDB} Enhanced Client
:info_abstract: About the {DDB} enhanced client in the {sdkjavav2}.
:info_keywordset: sdk-javacode examples enhanced client object mapper get items from {DDB} tables

[abstract]
--
About the {DDB} enhanced client in the {sdkjavav2}.
--

The {DDBlong} enhanced client is a high-level library that is part of the {sdk-java} version 2
(v2). It offers a straightforward way to map client-side classes to {DDB} tables. You define the
relationships between tables and their corresponding model classes in your code. Then you can
intuitively perform various create, read, update, or delete (CRUD) operations on tables or items
in {DDB}.

The {sdk-java} v2 includes a set of annotations that you can use with a Java bean to quickly
generate a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]
for mapping your classes to tables. Alternatively, if you declare each
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]
explicitly, you don't need to include annotations in your classes.


For information about how to use the {DDB} Enhanced Client, refer to
<<examples-dynamodb-enhanced, Mapping items in {DDB} tables>>.
