//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cloudwatch-use-alarm-actions,examples-cloudwatch-use-alarm-actions.title]]
= [[use-alarm-actions-in-cw, Using alarm actions]]Using alarm actions in {CW}
:info_doctype: section
:info_title: Using alarm actions in {CW}
:info_abstract: How to enable or disable alarm actions for {CWlong} with the {sdkjavav2}.
:info_keywordset: sdkjavav2code examples

[abstract]
--
How to enable or disable alarm actions for {CWlong} with the {sdkjavav2}.
--

Using {CW} alarm actions, you can create alarms that perform actions such as automatically
stopping, terminating, rebooting, or recovering {EC2} instances.

[NOTE]
====

Alarm actions can be added to an alarm by using the
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/PutMetricAlarmRequest.html[PutMetricAlarmRequest]'s
`alarmActions` method when
xref:examples-cloudwatch-create-alarms[creating an alarm,linkend=examples-cloudwatch-create-alarms].

====

[[enable-alarm-actions,enable-alarm-actions.title]]
== Enable alarm actions

To enable alarm actions for a {CW} alarm, call the CloudWatchClient's `enableAlarmActions` with a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/EnableAlarmActionsRequest.html[EnableAlarmActionsRequest]
containing one or more names of alarms whose actions you want to enable.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.enable_alarm_actions.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.enable_alarm_actions.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/EnableAlarmActions.java[complete example]
on GitHub.

[[disable-alarm-actions,disable-alarm-actions.title]]
== Disable alarm actions

To disable alarm actions for a {CW} alarm, call the CloudWatchClient's `disableAlarmActions` with a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/DisableAlarmActionsRequest.html[DisableAlarmActionsRequest]
containing one or more names of alarms whose actions you want to disable.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.disable_alarm_actions.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.disable_alarm_actions.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/DisableAlarmActions.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-cw-user}UsingAlarmActions.html[Create Alarms to Stop, Terminate, Reboot, or Recover an Instance] in the {guide-cw-user}
* {url-cw-api}API_PutMetricAlarm.html[PutMetricAlarm] in the {guide-cw-api}
* {url-cw-api}API_EnableAlarmActions.html[EnableAlarmActions] in the {guide-cw-api}
* {url-cw-api}API_DisableAlarmActions.html[DisableAlarmActions] in the {guide-cw-api}
