//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-ec2-security-groups,examples-ec2-security-groups.title]]
= [[work-with-security-groups-in-ec2, Work with security groups in EC2]]Work with security groups in {EC2}
:info_doctype: section
:info_title: Work with security groups in {EC2}
:info_abstract: How to create, configure and delete {EC2} security groups with the {sdkjavav2}.
:info_keywordset: sdkjavav2code examples {EC2} security groups create a security group ingress \
    rules egress rules IP permissions {EC2} access

[abstract]
--
How to create, configure and delete {EC2} security groups with the {sdkjavav2}.
--

[[create-a-security-group,create-a-security-group.title]]
== Create a security group

To create a security group, call the Ec2Client's `createSecurityGroup` method with a
{v2javadocs}software/amazon/awssdk/services/ec2/model/CreateSecurityGroupRequest.html[CreateSecurityGroupRequest]
that contains the key's name.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.create_security_group.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.create_security_group.create.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/CreateSecurityGroup.java[complete example]
on GitHub.

[[configure-a-security-group,configure-a-security-group.title]]
== Configure a security group

A security group can control both inbound (ingress) and outbound (egress) traffic to your {EC2}
instances.

To add ingress rules to your security group, use the Ec2Client's `authorizeSecurityGroupIngress`
method, providing the name of the security group and the access rules
({v2javadocs}software/amazon/awssdk/services/ec2/model/IpPermission.html[IpPermission])
you want to assign to it within an
{v2javadocs}software/amazon/awssdk/services/ec2/model/AuthorizeSecurityGroupIngressRequest.html[AuthorizeSecurityGroupIngressRequest]
object. The following example shows how to add IP permissions to a security group.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.create_security_group.import.txt[]
----

*Code*

First, create an Ec2Client

[source,java]
----
include::../../snippets/ec2.java2.create_security_group.client.txt[]
----

Then use the Ec2Client's `authorizeSecurityGroupIngress` method,

[source,java]
----
include::../../snippets/ec2.java2.create_security_group.config.txt[]
----

To add an egress rule to the security group, provide similar data in an
{v2javadocs}software/amazon/awssdk/services/ec2/model/AuthorizeSecurityGroupEgressRequest.html[AuthorizeSecurityGroupEgressRequest]
to the Ec2Client's `authorizeSecurityGroupEgress` method.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/CreateSecurityGroup.java[complete example]
on GitHub.

[[describe-security-groups,describe-security-groups.title]]
== Describe security groups

To describe your security groups or get information about them, call the Ec2Client's
`describeSecurityGroups` method. It returns a
{v2javadocs}software/amazon/awssdk/services/ec2/model/DescribeSecurityGroupsResponse.html[DescribeSecurityGroupsResponse]
that you can use to access the list of security groups by calling its `securityGroups` method,
which returns a list of
{v2javadocs}software/amazon/awssdk/services/ec2/model/SecurityGroup.html[SecurityGroup]
objects.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.describe_security_groups.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.describe_security_groups.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/DescribeSecurityGroups.java[complete example]
on GitHub.

[[delete-a-security-group,delete-a-security-group.title]]
== Delete a security group

To delete a security group, call the Ec2Client's `deleteSecurityGroup` method, passing it a
{v2javadocs}software/amazon/awssdk/services/ec2/model/DeleteSecurityGroupRequest.html[DeleteSecurityGroupRequest]
that contains the ID of the security group to delete.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.delete_security_group.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.delete_security_group.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/DeleteSecurityGroup.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-ec2-user}ec2-key-pairs.html[{EC2} Security Groups] in the {guide-ec2-user}
* {url-ec2-user}authorizing-access-to-an-instance.html[Authorizing Inbound Traffic for Your Linux Instances] in the {guide-ec2-user}
* link:AWSEC2/latest/APIReference/API_CreateSecurityGroup.html["CreateSecurityGroup", type="documentation"] in the {guide-ec2-api}
* link:AWSEC2/latest/APIReference/API_DescribeSecurityGroups.html["DescribeSecurityGroups", type="documentation"] in the {guide-ec2-api}
* link:AWSEC2/latest/APIReference/API_DeleteSecurityGroup.html["DeleteSecurityGroup", type="documentation"] in the {guide-ec2-api}
* link:AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html["AuthorizeSecurityGroupIngress", type="documentation"] in the {guide-ec2-api}
