//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-s3-presign,examples-s3-presign.title]]
= [[working-with-amazon-s3-presigned-urls, Working with S3 presigned URLs]]Working with {S3} presigned URLs
:info_doctype: section
:info_title: Working with {S3} presigned URLs
:info_titleabbrev: Presigned URLs
:info_abstract: How to work with presigned buckets using the {sdkjavav2}.
:info_keywordset: S3long{S3} {sdkjavav2} S3 code examples CreateBucketRequest \
    ListBucketRequest ListObjectsV2Request

[abstract]
--
How to work with Presigned buckets using the {sdkjavav2}.
--

You can use a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/S3Presigner.html[S3Presigner]
object to sign an {S3}``SdkRequest`` so that it's executed without requiring authentication on
the part of the caller. For example, assume Alice has access to an S3 object, and she wants to
temporarily share access to that object with Bob. Alice can generate a pre-signed
{v2javadocs}software/amazon/awssdk/services/s3/model/GetObjectRequest.html[GetObjectRequest]
object to secure share with Bob so that he can download the object without requiring access to
Alice's credentials.

[.topiclist-abbrev]
[[Topic List]]


[[generate-presignedurl,generate-presignedurl.title]]
== Generate a Presigned URL and Upload an Object

Build a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/S3Presigner.html[S3Presigner]
object that represents the client object. Next create a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/model/PresignedPutObjectRequest.html[PresignedPutObjectRequest]
object that can be executed at a later time without requiring additional signing or
authentication. When you create this object, you can specify the bucket name and the key name. In
addition, you can also specify the time in minutes that the bucket can be accessed without using
credentials by invoking the `signatureDuration` method (as shown in the following code example).

You can use the
{v2javadocs}software/amazon/awssdk/services/s3/presigner/model/PresignedPutObjectRequest.html[PresignedPutObjectRequest]
object to obtain the URL by invoking its `url` method.

*Imports*

[source,java]
----
include::../../snippets/presigned.java2.generatepresignedurl.import.txt[]
----

*Code*

The following Java code example uploads content to a presigned S3 bucket.

[source,java]
----
include::../../snippets/presigned.java2.generatepresignedurl.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/GeneratePresignedUrlAndUploadObject.java[complete example]
on GitHub.

[[get-presignedobject,get-presignedobject.title]]
== Get a Presigned Object

Build a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/S3Presigner.html[S3Presigner]
object that represents the client object. Next, create a
{v2javadocs}software/amazon/awssdk/services/s3/model/GetObjectRequest.html[GetObjectRequest]
object and specify the bucket name and key name. In addition, create a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/model/GetObjectPresignRequest.html[GetObjectPresignRequest]
object that can be executed at a later time without requiring additional signing or
authentication. When you create this object, you can specify the time in minutes that the bucket
can be accessed without using credentials by invoking the `signatureDuration` method (as shown in
the following code example).

Invoke the `presignGetObject` method that belongs to the
{v2javadocs}software/amazon/awssdk/services/s3/presigner/S3Presigner.html[S3Presigner]
object to create a
{v2javadocs}software/amazon/awssdk/services/s3/presigner/model/PresignedPutObjectRequest.html[PresignedPutObjectRequest]
object. You can invoke this object's `url` method to obtain the URL to use. Once you have the
URL, you can use standard HTTP Java logic to read the contents of the bucket, as shown in the
following Java code example.

*Imports*

[source,java]
----
include::../../snippets/presigned.java2.getobjectpresigned.import.txt[]
----

*Code*

The following Java code example reads content from a presigned S3 bucket.

[source,java]
----
include::../../snippets/presigned.java2.getobjectpresigned.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/GetObjectPresignedUrl.java[complete example]
on GitHub.