//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-sqs-messages,examples-sqs-messages.title]]
= [[sending-receiving-and-deleting-sqs-messages, Sending, receiving, and deleting SQS messages]]Sending, receiving, and deleting {SQSlong} messages
:info_doctype: section
:info_title: Sending, receiving, and deleting {SQSlong} messages
:info_titleabbrev: Message operations
:info_abstract: How to send, receive and delete {SQSlong} messages.
:info_keywordset: sdk-javacode examples{SQSlong} send message receive message delete message \
    SendMessageRequest ReceiveMessageRequest

[abstract]
--
How to send, receive and delete {SQSlong} messages.
--

A message is a piece of data that can be sent and received by distributed components. Messages
are always delivered using an
xref:examples-sqs-message-queues[SQS Queue,linkend=examples-sqs-message-queues].

[[sqs-message-send,sqs-message-send.title]]
== Send a message

Add a single message to an {SQSlong} queue by calling the SqsClient client `sendMessage` method.
Provide a
{v2javadocs}software/amazon/awssdk/services/sqs/model/SendMessageRequest.html[SendMessageRequest]
object that contains the queue's
xref:sqs-get-queue-url[URL,linkend=sqs-get-queue-url],
message body, and optional delay value (in seconds).

*Imports*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.send_message.txt[]
----


[[sqs-messages-send-multiple,sqs-messages-send-multiple.title]]
== Send multiple messages in a request

Send more than one message in a single request by using the SqsClient ``sendMessageBatch`` method.
This method takes a
{v2javadocs}software/amazon/awssdk/services/sqs/model/SendMessageBatchRequest.html[SendMessageBatchRequest]
that contains the queue URL and a list of messages to send. (Each message is a
{v2javadocs}software/amazon/awssdk/services/sqs/model/SendMessageBatchRequestEntry.html[SendMessageBatchRequestEntry].)
You can also delay sending a specific message by setting a delay value on the message.

*Imports*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.send__multiple_messages.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/sqs/src/main/java/com/example/sqs/SQSExample.java[complete sample]
on GitHub.

[[sqs-messages-receive,sqs-messages-receive.title]]
== Retrieve Messages

Retrieve any messages that are currently in the queue by calling the SqsClient ``receiveMessage``
method. This method takes a
{v2javadocs}software/amazon/awssdk/services/sqs/model/ReceiveMessageRequest.html[ReceiveMessageRequest]
that contains the queue URL. You can also specify the maximum number of messages to return.
Messages are returned as a list of
{v2javadocs}software/amazon/awssdk/services/sqs/model/Message.html[Message]
objects.

*Imports*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.retrieve_messages.txt[]
----


[[sqs-messages-delete,sqs-messages-delete.title]]
== Delete a message after receipt

After receiving a message and processing its contents, delete the message from the queue by
sending the message's receipt handle and queue URL to the SqsClient ``deleteMessage`` method.

*Imports*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/sqs.java2.sqs_example.delete_message.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/sqs/src/main/java/com/example/sqs/SQSExample.java[complete sample]
on GitHub.

[[more-info,more-info.title]]
== More Info

* link:AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-how-it-works.html["How pass:q[[.shared\]`SQSlong`] Queues Work", type="documentation"] in the {guide-sqs-dev}
* link:AWSSimpleQueueService/latest/APIReference/API_SendMessage.html["SendMessage", type="documentation"] in the {guide-sqs-api}
* link:AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html["SendMessageBatch", type="documentation"] in the {guide-sqs-api}
* link:AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html["ReceiveMessage", type="documentation"] in the {guide-sqs-api}
* link:AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html["DeleteMessage", type="documentation"] in the {guide-sqs-api}
