//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cloudwatch-get-metrics,examples-cloudwatch-get-metrics.title]]
= [[get-metrics-from-cw, Get metrics from CloudWatch]]Get metrics from {CW}
:info_doctype: section
:info_title: Getting metrics from {CW}
:info_abstract: How to list metrics from {CWlong} using the {sdkjavav2}
:info_keywordset: CWlong{sdk-java} metrics listing {sdkjavav2} code examples

[abstract]
--
How to list metrics from {CWlong} using the {sdkjavav2}
--

[[listing-metrics,listing-metrics.title]]
== Listing metrics

To list {CW} metrics, create a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/ListMetricsRequest.html[ListMetricsRequest]
and call the CloudWatchClient's `listMetrics` method. You can use the `ListMetricsRequest` to
filter the returned metrics by namespace, metric name, or dimensions.

[NOTE]
====

A list of metrics and dimensions that are posted by {AWS-services} can be found within the
{url-cw-user}CW_Support_For_AWS.html[{CWlong} Metrics and Dimensions Reference]
in the {guide-cw-user}.

====

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.list_metrics.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.list_metrics.main.txt[]
----

The metrics are returned in a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/ListMetricsResponse.html[ListMetricsResponse]
by calling its `getMetrics` method.

The results may be __paged__. To retrieve the next batch of results, call `nextToken` on the
response object and use the token value to build a new request object. Then call the
`listMetrics` method again with the new request.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/ListMetrics.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-cw-api}API_ListMetrics.html[ListMetrics] in the
{guide-cw-api}
