//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-ec2-key-pairs,examples-ec2-key-pairs.title]]
= [[work-with-ec2-key-pairs, Work with EC2 key pairs]]Work with {EC2} key pairs
:info_doctype: section
:info_title: Work with {EC2} key pairs
:info_abstract: How to create, list and delete {EC2} key pairs using the {sdkjavav2}.
:info_keywordset: sdkjavav2code examples {EC2} key pairs create key pair list key pairs delete \
    key pair

[abstract]
--
How to create, list and delete {EC2} key pairs using the {sdkjavav2}.
--

[[create-a-key-pair,create-a-key-pair.title]]
== Create a key pair

To create a key pair, call the Ec2Client's `createKeyPair` method with a
{v2javadocs}software/amazon/awssdk/services/ec2/model/CreateKeyPairRequest.html[CreateKeyPairRequest]
that contains the key's name.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.create_key_pair.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.create_key_pair.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/CreateKeyPair.java[complete example]
on GitHub.

[[describe-key-pairs,describe-key-pairs.title]]
== Describe key pairs

To list your key pairs or to get information about them, call the Ec2Client's `describeKeyPairs`
method. It returns a
{v2javadocs}software/amazon/awssdk/services/ec2/model/DescribeKeyPairsResponse.html[DescribeKeyPairsResponse]
that you can use to access the list of key pairs by calling its `keyPairs` method, which returns
a list of
{v2javadocs}software/amazon/awssdk/services/ec2/model/KeyPairInfo.html[KeyPairInfo]
objects.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.describe_key_pairs.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.describe_key_pairs.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/DescribeKeyPairs.java[complete example]
on GitHub.

[[delete-a-key-pair,delete-a-key-pair.title]]
== Delete a key pair

To delete a key pair, call the Ec2Client's `deleteKeyPair` method, passing it a
{v2javadocs}software/amazon/awssdk/services/ec2/model/DeleteKeyPairRequest.html[DeleteKeyPairRequest]
that contains the name of the key pair to delete.

*Imports*

[source,java]
----
include::../../snippets/ec2.java2.delete_key_pair.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/ec2.java2.delete_key_pair.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/ec2/src/main/java/com/example/ec2/DeleteKeyPair.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-ec2-user}ec2-key-pairs.html[{EC2} Key Pairs] in the {guide-ec2-user}
* link:AWSEC2/latest/APIReference/API_CreateKeyPair.html["CreateKeyPair", type="documentation"] in the {guide-ec2-api}
* link:AWSEC2/latest/APIReference/API_DescribeKeyPairs.html["DescribeKeyPairs", type="documentation"] in the {guide-ec2-api}
* link:AWSEC2/latest/APIReference/API_DeleteKeyPair.html["DeleteKeyPair", type="documentation"] in the {guide-ec2-api}
