//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cloudwatch-create-alarms,examples-cloudwatch-create-alarms.title]]
= [[work-with-cw-alarms, Working with CloudWatch alarms]]Working with {CW} alarms
:info_doctype: section
:info_title: Working with {CW} alarms
:info_abstract: How to create, list, and delete alarms in {CWlong} using the {sdkjavav2}
:info_keywordset: sdkjavav2examplecode

[abstract]
--
How to create, list, and delete alarms in {CWlong} using the {sdkjavav2}
--

[[create-an-alarm,create-an-alarm.title]]
== Create an alarm

To create an alarm based on a {CW} metric, call the CloudWatchClient's `putMetricAlarm` method
with a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/PutMetricAlarmRequest.html[PutMetricAlarmRequest]
filled with the alarm conditions.

*Imports*

[source,java,subs=attributes]
----
include::../../snippets/cloudwatch.java2.put_metric_alarm.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_metric_alarm.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/PutMetricAlarm.java[complete example]
on GitHub.

[[list-alarms,list-alarms.title]]
== List alarms

To list the {CW} alarms that you have created, call the CloudWatchClient's `describeAlarms`
method with a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/DescribeAlarmsRequest.html[DescribeAlarmsRequest]
that you can use to set options for the result.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.describe_alarms.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.describe_alarms.main.txt[]
----

The list of alarms can be obtained by calling `MetricAlarms` on the
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/DescribeAlarmsResponse.html[DescribeAlarmsResponse]
that is returned by ``describeAlarms``.

The results may be __paged__. To retrieve the next batch of results, call `nextToken` on the
response object and use the token value to build a new request object. Then call the
`describeAlarms` method again with the new request.

[NOTE]
====

You can also retrieve alarms for a specific metric by using the CloudWatchClient's
`describeAlarmsForMetric` method. Its use is similar to ``describeAlarms``.

====

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/DescribeAlarms.java[complete example]
on GitHub.

[[delete-alarms,delete-alarms.title]]
== Delete alarms

To delete {CW} alarms, call the CloudWatchClient's `deleteAlarms` method with a
{v2javadocs}software/amazon/awssdk/services/cloudwatch/model/DeleteAlarmsRequest.html[DeleteAlarmsRequest]
containing one or more names of alarms that you want to delete.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.delete_metrics.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.delete_metrics.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/DeleteAlarm.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-cw-user}AlarmThatSendsEmail.html[Creating {CWlong} Alarms] in the {guide-cw-user}
* {url-cw-api}API_PutMetricAlarm.html[PutMetricAlarm] in the {guide-cw-api}
* {url-cw-api}API_DescribeAlarms.html[DescribeAlarms] in the {guide-cw-api}
* {url-cw-api}API_DeleteAlarms.html[DeleteAlarms] in the {guide-cw-api}
