//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cloudwatch,examples-cloudwatch.title]]
= [[working-with-cw, Working with CloudWatch]]Working with {CW}
:info_doctype: section
:info_title: Working with {CW}
:info_titleabbrev: {CWlong}
:info_abstract: How to use the {sdk-java} to work with {CWlong}
:info_keywordset: sdkjavav2code examples{CW}

[abstract]
--
How to use the {sdk-java} to work with {CWlong}
--

This section provides examples of programming link:cloudwatch/["pass:q[[.shared\]`CW`]", type="marketing"] by using
the {sdkjavav2}.

{CWlong} monitors your {AWSlong} ({AWS}) resources and the applications you run on {AWS} in real
time. You can use {CW} to collect and track metrics, which are variables you can measure for your
resources and applications. {CW} alarms send notifications or automatically make changes to the
resources you are monitoring based on rules that you define.

For more information about {CW}, see the
{link-cw-user}.

The following examples include only the code needed to demonstrate each technique. The
{url-awsdocs-github}aws-doc-sdk-examples/tree/master/javav2[complete example code is available on GitHub].
From there, you can download a single source file or clone the repository locally to get all the
examples to build and run.

[.topiclist-abbrev]
[[Topic List]]


include::examples-cloudwatch-get-metrics.adoc[leveloffset=+1]


include::examples-cloudwatch-publish-custom-metrics.adoc[leveloffset=+1]


include::examples-cloudwatch-create-alarms.adoc[leveloffset=+1]


include::examples-cloudwatch-use-alarm-actions.adoc[leveloffset=+1]


include::examples-cloudwatch-send-events.adoc[leveloffset=+1]
