//!!NODE_ROOT <section>
include::../../includes.txt[]
:java-oracle-map: https://docs.oracle.com/javase/8/docs/api/index.html?java/util/Map.html
[."topic"]
[[examples-dynamodb-items,examples-dynamodb-items.title]]
= [[work-with-items-in-ddb, Working with items in DynamoDB]]Working with items in {DDB}
:info_doctype: section
:info_title: Working with items in {DDB}
:info_abstract: How to retrieve (get), add, and update items in {DDBlong} tables.
:info_keywordset: sdk-javacode examples items from {DDB} tables

[abstract]
--
How to retrieve (get), add, and update items in {DDBlong} tables.
--

In {DDB}, an item is a collection of __attributes__, each of which has a _name_ and a __value__.
An attribute value can be a scalar, set, or document type. For more information, see
{url-ddb-dev}HowItWorks.NamingRulesDataTypes.html[Naming Rules and Data Types]
in the {guide-ddb-dev}.

[[dynamodb-get-item,dynamodb-get-item.title]]
== Retrieve (get) an item from a table

Call the DynamoDbClient's `getItem` method and pass it a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/GetItemRequest.html[GetItemRequest]
object with the table name and primary key value of the item you want. It returns a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/GetItemResponse.html[GetItemResponse]
object with all of the attributes for that item. You can specify one or more
{url-ddb-dev}Expressions.ProjectionExpressions.html[projection expressions]
in the `GetItemRequest` to retrieve specific attributes.

You can use the returned `GetItemResponse` object's `item()` method to retrieve a
{java-oracle-map}[Map] of key (String) and value
({v2javadocs}software/amazon/awssdk/services/dynamodb/model/AttributeValue.html[AttributeValue])
pairs that are associated with the item.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.get_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.get_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/GetItem.java[complete example]
on GitHub.

[[id1ddb,id1ddb.title]]
== Retrieve (get) an item from a table using the asynchronous client

Invoke the `getItem` method of the DynamoDbAsyncClient and pass it a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/GetItemRequest.html[GetItemRequest]
object with the table name and primary key value of the item you want.

You can return a {java-oracle-collection}[Collection] instance with all of the attributes for
that item (refer to the following example).

*Imports*

[source,java]
----
include::../../snippets/dynamoasyn.java2.get_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamoasyc.java2.get_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodbasync/src/main/java/com/example/dynamodbasync/DynamoDBAsyncGetItem.java[complete example]
on GitHub.

[[dynamodb-add-item,dynamodb-add-item.title]]
== Add a new item to a table

Create a {java-oracle-map}[Map] of key-value pairs that represent the item's attributes. These
must include values for the table's primary key fields. If the item identified by the primary key
already exists, its fields are _updated_ by the request.

[NOTE]
====

If the named table doesn't exist for your account and region, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.put_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.put_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/PutItem.java[complete example]
on GitHub.

[[dynamodb-update-item,dynamodb-update-item.title]]
== Update an existing item in a table

You can update an attribute for an item that already exists in a table by using the
DynamoDbClient's `updateItem` method, providing a table name, primary key value, and a map of
fields to update.

[NOTE]
====

If the named table doesn't exist for your account and region, or if the item identified by the
primary key you passed in doesn't exist, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.update_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.update_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/UpdateItem.java[complete example]
on GitHub.

[[dynamodb-delete-item,dynamodb-delete-item.title]]
== Delete an existing item in a table

You can delete an item that exists in a table by using the DynamoDbClient's `deleteItem` method
and providing a table name as well as the primary key value.

[NOTE]
====

If the named table doesn't exist for your account and region, or if the item identified by the
primary key you passed in doesn't exist, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.delete_item.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.delete_item.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/DeleteItem.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-ddb-dev}GuidelinesForItems.html[Guidelines for Working with Items] in the {guide-ddb-dev}
* {url-ddb-dev}WorkingWithItems.html[Working with Items in {DDB}] in the {guide-ddb-dev}
