//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cloudwatch-send-events,examples-cloudwatch-send-events.title]]
= [[send-events-to-cw, Sending events]]Sending events to {CW}
:info_doctype: section
:info_title: Sending events to {CW}
:info_abstract: How to add events, rules and rule targets for {CWlong} using the {sdkjavav2}.
:info_keywordset: sdkjavav2code examples

[abstract]
--
How to add events, rules and rule targets for {CWlong} using the {sdkjavav2}.
--

{CWE} delivers a near real-time stream of system events that describe changes in {AWS}
resources to {EC2} instances, {LAM} functions, {AK} streams, {ECS} tasks, {SFN} state machines,
{SNS} topics, {SQS} queues, or built-in targets. You can match events and route them to one or
more target functions or streams by using simple rules.

[[add-events,add-events.title]]
== Add events

To add custom {CW} events, call the CloudWatchEventsClient's `putEvents` method with a
{v2javadocs}software/amazon/awssdk/services/cloudwatchevents/model/PutEventsRequest.html[PutEventsRequest]
object that contains one or more
{v2javadocs}software/amazon/awssdk/services/cloudwatchevents/model/PutEventsRequestEntry.html[PutEventsRequestEntry]
objects that provide details about each event. You can specify several parameters for the entry
such as the source and type of the event, resources associated with the event, and so on.

[NOTE]
====

You can specify a maximum of 10 events per call to ``putEvents``.

====

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_events.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_events.main.txt[]
----

See the {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/PutEvents.java[complete example] on GitHub.

[[add-rules,add-rules.title]]
== Add rules

To create or update a rule, call the CloudWatchEventsClient's `putRule` method with a
{v2javadocs}software/amazon/awssdk/services/cloudwatchevents/model/PutRuleRequest.html[PutRuleRequest]
with the name of the rule and optional parameters such as the
link:AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html["event pattern", type="documentation"],
{IAM} role to associate with the rule, and a
link:AmazonCloudWatch/latest/events/ScheduledEvents.html["scheduling expression", type="documentation"]
that describes how often the rule is run.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_rule.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_rule.main.txt[]
----

See the {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/PutRule.java[complete example] on GitHub.

[[add-targets,add-targets.title]]
== Add targets

Targets are the resources that are invoked when a rule is triggered. Example targets include
{EC2} instances, {LAM} functions, {AK} streams, {ECS} tasks, {SFN} state machines, and built-in targets.

To add a target to a rule, call the CloudWatchEventsClient's `putTargets` method with a
{v2javadocs}software/amazon/awssdk/services/cloudwatchevents/model/PutTargetsRequest.html[PutTargetsRequest] containing the rule to update and a list of targets to add to the rule.

*Imports*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_targets.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cloudwatch.java2.put_targets.main.txt[]
----

See the {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/PutTargets.java[complete example] on GitHub.

[[more-information,more-information.title]]
== More information

* link:AmazonCloudWatch/latest/events/AddEventsPutEvents.html["Adding Events with PutEvents", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/ScheduledEvents.html["Schedule Expressions for Rules", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/EventTypes.html["Event Types for pass:q[[.shared\]`CWE`]", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html["Events and Event Patterns", type="documentation"] in the {guide-cwe-user}
* link:AmazonCloudWatchEvents/latest/APIReference/API_PutEvents.html["PutEvents", type="documentation"] in the {guide-cwe-api}
* link:AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html["PutTargets", type="documentation"] in the {guide-cwe-api}
* link:AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html["PutRule", type="documentation"] in the {guide-cwe-api}
