//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-dynamodb-enhanced,examples-dynamodb-enhanced.title]]
= [[map-items-in-ddb-tables, Mapping items in DynamoDB tables]]Mapping items in {DDB} tables
:info_doctype: section
:info_title: Mapping items in {DDB} tables
:info_abstract: How to use the {DDB} enhanced client to map client-side items to records in {DDB} \
tables.
:info_keywordset: sdk-javacode examples enhanced client object mapper get items from {DDB} tables

[abstract]
--
How to use the {DDB} enhanced client to map client-side items to records in {DDB} tables.
--

The {DDBlong} enhanced client is a high-level library that is part of the {sdk-java} version 2
(v2). It offers a straightforward way to map client-side classes to {DDB} tables. You define the
relationships between tables and their corresponding model classes in your code. Then you can
intuitively perform various create, read, update, or delete (CRUD) operations on tables or items
in {DDB}.

The {sdk-java} v2 includes a set of annotations that you can use with a Java bean to quickly
generate a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]
for mapping your classes to tables. Alternatively, if you declare each
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]
explicitly, you don't need to include annotations in your classes.

To work with items in a {DDB} table using the enhanced client, first create a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.html[DynamoDbEnhancedClient]
from an existing
{v2javadocs}software/amazon/awssdk/services/dynamodb/DynamoDbClient.html[DynamoDbClient]
object.

[source,java]
----
Region region = Region.US_EAST_1;
DynamoDbClient ddb = DynamoDbClient.builder()
        .region(region)
        .build();

DynamoDbEnhancedClient enhancedClient = DynamoDbEnhancedClient.builder()
        .dynamoDbClient(ddb)
        .build();

createDynamoDBTable(enhancedClient);
----


[[dynamodb-enhanced-mapper-beantable,dynamodb-enhanced-mapper-beantable.title]]
== Create a table using the enhanced client

To easily create a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]
using the enhanced client, start by creating a Java data class that includes a default public
constructor and standardized names of getters and setters for each property in the class. Include
a class-level annotation to indicate it is a `DynamoDbBean` and, at a minimum, include a
`DynamoDbPartitionKey` annotation on the getter or setter for the primary key of the table record.

Once this data class has been defined, call
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/TableSchema.html[TableSchema]'s
`fromBean()` with that data class to create the table schema.

See the code snippet below for an example of how to do this.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.putitem.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.putitem.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedPutItem.java[complete example]
on GitHub.

[[dynamodb-enhanced-mapper-getitem,dynamodb-enhanced-mapper-getitem.title]]
== Retrieve (get) an item from a table

To get an item from a {DDB} table, create a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html[DynamoDbTable]
object and call `getItem()` with a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/GetItemEnhancedRequest.html[GetItemEnhancedRequest]
object to get the actual item.

For example, the following code snippet demonstrates one way to use the enhanced client to get
information from an item in a {DDB} table.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.getitem.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.getitem.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedGetItem.java[complete example]
on GitHub.

[[dynamodb-enhanced-mapper-batchitems,dynamodb-enhanced-mapper-batchitems.title]]
== Batch create (put) and delete items

You can batch a series of put requests
({v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedRequest.html[PutItemEnhancedRequest])
and delete requests
({v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedRequest.html[DeleteItemEnhancedRequest])
to one or more tables, and then send all of the changes in a single request.

In the following code snippet, a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html[DynamoDbTable]
object is created, two items are queued up to be added to the table, and then the items are
written to the table in a single call. Include multiple entries of `addDeleteItem()` and
`addPutItem()`
({v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/WriteBatch.Builder.html[part of WriteBatch.Builder])
in each batch, as needed. To queue up changes to a different table, add another instance of
`WriteBatch.builder()` and provide a corresponding
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html[DynamoDbTable]
object in ``mappedTableResource()``.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.batchitems.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.batchitems.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedBatchWriteItems.java[complete example]
on GitHub.

[[dynamodb-enhanced-mapper-queryfilter,dynamodb-enhanced-mapper-queryfilter.title]]
== Use a filtered query to get items from a table

You can get items from a table based on filterable queries, and then perform operations (for
example, return item values) on one or more of the items in the query results.

In the following code snippet, you build a filter by first defining the value or values you're
searching for as an
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/AttributeValue.html[AttributeValue]
object. Then you put this into a `HashMap` and build an
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/Expression.html[Expression]
from the `HashMap`. Build a
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/QueryConditional.html[QueryConditional]
object to specify the primary key to match against in the query, and then execute the query on
your
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html[DynamoDbTable]
object.

[NOTE]
====

The
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/model/QueryConditional.html[QueryConditional]
interface has several methods you can use to build your queries, including common conditional
statements like greater than, less than, and in between.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.queryfilter.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.queryfilter.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedQueryRecordsWithFilter.java[complete example]
on GitHub.

[[dynamodb-enhanced-mapper-scan,dynamodb-enhanced-mapper-scan.title]]
== Retrieve (get) all items from a table

When you want to get all of the records in a given {DDB} table, use the `scan()` method of your
{v2javadocs}software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html[DynamoDbTable]
object and the `items()` method to create a set of results against which you can execute various
item operations. For example, the following code snippet prints out the ID value of each item in
the *Record* table.

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.scan.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.mapping.scan.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedScanRecords.java[complete example]
on GitHub.

For more information, see
{url-ddb-dev}WorkingWithItems.html[Working with items in {DDB}]
in the {guide-ddb-dev}.