//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-cognito,examples-cognito.title]]
= [[working-with-cog, Working with Cognito]]Working with {COGlong}
:info_doctype: section
:info_title: Working with {COG}
:info_titleabbrev: {COGlong}
:info_abstract: How to use the {sdk-java} to work with {COGlong}
:info_keywordset: sdk-javacode examples cognito user pool app \
    client identity IdP provider credentials

[abstract]
--
How to use the {sdk-java} to work with {COGlong}
--

With {COGlong}, you can quickly add user sign-up or sign-in capability to your web or mobile app.
The examples here demonstrate some of the basic functionality of {COG}.

[[cognito-create-userpool,cognito-create-userpool.title]]
== Create a user pool

A user pool is a directory of users that you can configure for your web or mobile app.

To create a user pool, start by building a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/CreateUserPoolRequest.html[CreateUserPoolRequest]
object, with the name of the user pool as the value of its ``poolName()``. Call the
`createUserPool()` method of your
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/CognitoIdentityProviderClient.html[CreateUserPoolRequest],
passing in the `CreateUserPoolRequest` object. You can capture the result of this request as a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/CreateUserPoolResponse.html[CreateUserPoolResponse]
object, as demonstrated in the following code snippet.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.create_user_pool.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.create_user_pool.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/CreateUserPool.java[complete example]
on GitHub.

[[cognito-list-userpool,cognito-list-userpool.title]]
== List users from a user pool

To list users from your user pools, start by building a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/ListUserPoolsRequest.html[ListUserPoolsRequest]
object, with the number of maximum results as the value of its ``maxResults()``. Call the
`listUserPools()` method of your ``CognitoIdentityProviderClient``, passing in the
`ListUserPoolsRequest` object. You can capture the result of this request as a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/ListUserPoolsResponse.html[ListUserPoolsResponse]
object, as demonstrated in the following code snippet. Create a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/UserPoolDescriptionType.html[UserPoolDescriptionType]
object to easily iterate over the results and pull out the attributes of each user.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.ListUserPools.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.ListUserPools.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/ListUserPools.java[complete example]
on GitHub.

[[cognito-create-identitypool,cognito-create-identitypool.title]]
== Create an identity pool

An identity pool is a container that organizes the IDs from your external identity provider,
keeping a unique identifier for each user. To create an identity pool, start by building a
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/CreateIdentityPoolRequest.html[CreateIdentityPoolRequest]
with the name of the user pool as the value of its ``identityPoolName()``. Set
`allowUnauthenticatedIdentities()` to `true` or ``false``. Call the `createIdentityPool()` method
of your `CognitoIdentityClient` object, passing in the `CreateIdentityPoolRequest` object. You
can capture the result of this request as a
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/CreateIdentityPoolResponse.html[CreateIdentityPoolResponse]
object, as demonstrated in the following code snippet.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.create_identity_pool.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.create_identity_pool.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/CreateIdentityPool.java[complete example]
on GitHub.

[[cognito-add-appclient,cognito-add-appclient.title]]
== Add an app client

To enable the hosted web sign-up or sign-in UI for your app, create an app client. To create an
app client, start by building a
{v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/CreateUserPoolClientRequest.html[CreateUserPoolClientRequest] object, with the name of the client as the value of its ``clientName()``. Set `userPoolId()` to the ID of the user pool to which you want to attach this app client. Call the `createUserPoolClient()` method of your ``CognitoIdentityProviderClient``, passing in the `CreateUserPoolClientRequest` object. You can capture the result of this request as a {v2javadocs}software/amazon/awssdk/services/cognitoidentityprovider/model/CreateUserPoolClientResponse.html[CreateUserPoolClientResponse]
object, as demonstrated in the following code snippet.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.user_pool.create_user_pool_client.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.user_pool.create_user_pool_client.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/CreateUserPoolClient.java[complete example]
on GitHub.

[[cognito-thirdparty-idp,cognito-thirdparty-idp.title]]
== Add a third-party identity provider

Adding an external identity provider (IdP) enables your users to log into your app using that
service's login mechanism. To add a third-party IdP, start by building an
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/UpdateIdentityPoolRequest.html[UpdateIdentityPoolRequest]
object, with the name of the identity pool as the value of its ``identityPoolName()``. Set
`allowUnauthenticatedIdentities()` to `true` or ``false``, specify the ``identityPoolId()``, and
define which login providers will be supported with ``supportedLoginProviders()``. Call the
`updateIdentityPool()` method of your ``CognitoIdentityClient``, passing in the
`UpdateIdentityPoolRequest` object. You can capture the result of this request as an
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/UpdateIdentityPoolResponse.html[UpdateIdentityPoolResponse]
object, as demonstrated in the following code snippet.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.add_login_provider.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.add_login_provider.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/AddLoginProvider.java[complete example]
on GitHub.

[[cognito-get-credentials,cognito-get-credentials.title]]
== Get credentials for an ID

To get the credentials for an identity in an identity pool, first build a
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/GetCredentialsForIdentityRequest.html[GetCredentialsForIdentityRequest]
with the identity ID as the value of its ``identityId()``. Call the `getCredentialsForIdentity()`
method of your ``CognitoIdentityClient``, passing in the ``GetCredentialsForIdentityRequest``.
You can capture the result of this request as a
{v2javadocs}software/amazon/awssdk/services/cognitoidentity/model/GetCredentialsForIdentityResponse.html[GetCredentialsForIdentityResponse]
object, as demonstrated in the following code snippet.

*Imports*

[source,java]
----
include::../../snippets/cognito.java2.GetIdentityCredentials.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/cognito.java2.GetIdentityCredentials.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/cognito/src/main/java/com/example/cognito/GetIdentityCredentials.java[complete example]
on GitHub.

For more information, see the {link-cog-dev}.