//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-s3-buckets,examples-s3-buckets.title]]
= [[creating-listing-and-deleting-s3-buckets, Creating, listing, and deleting S3 buckets]]Creating, listing, and deleting {S3} buckets
:info_doctype: section
:info_title: Creating, listing, and deleting {S3} buckets
:info_titleabbrev: Bucket operations
:info_abstract: How to create, list, or delete a bucket using the {sdkjavav2}.
:info_keywordset: S3long{S3} {sdkjavav2} S3 code examples \
    CreateBucketRequest ListBucketRequest ListObjectsV2Request

[abstract]
--
How to create, list, or delete a bucket using the {sdkjavav2}.
--

Every object (file) in {S3} must reside within a __bucket__. A bucket represents a collection
(container) of objects. Each bucket must have a unique _key_ (name). For detailed information
about buckets and their configuration, see
{url-s3-dev}UsingBucket.html[Working with {S3} Buckets] in the {guide-s3-dev}.

[NOTE]
====

Best Practice

We recommend that you enable the
{url-s3-api}RESTBucketPUTlifecycle.html[AbortIncompleteMultipartUpload] lifecycle rule on your
{S3} buckets.

This rule directs {S3} to abort multipart uploads that don't complete within a specified number
of days after being initiated. When the set time limit is exceeded, {S3} aborts the upload and
then deletes the incomplete upload data.

For more information, see
{url-s3-user}lifecycle-configuration-bucket-with-versioning.html[Lifecycle Configuration for a Bucket with Versioning]
in the {guide-s3-user}.

====

[NOTE]
====

These code snippets assume that you understand the material in basics, and have configured
default {AWS} credentials using the information in xref:setup-credentials[].

====

[.topiclist-abbrev]
[[Topic List]]


[[create-bucket,create-bucket.title]]
== Create a bucket

Build a
{v2javadocs}software/amazon/awssdk/services/s3/model/CreateBucketRequest.html[CreateBucketRequest]
and provide a bucket name. Pass it to the S3Client's `createBucket` method.
Use the `S3Client` to do additional operations such as listing or deleting buckets as shown in
later examples.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.import.txt[]
----

*Code*

First create an S3Client.

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.region.txt[]
----

Make a Create Bucket Request.

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.create_bucket.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3BucketOps.java[complete example]
on GitHub.

[[list-buckets,list-buckets.title]]
== List the buckets

Build a
{v2javadocs}software/amazon/awssdk/services/s3/model/ListBucketsRequest.html[ListBucketsRequest].
Use the S3Client's `listBuckets` method to retrieve the list of buckets. If the request succeeds a
{v2javadocs}software/amazon/awssdk/services/s3/model/ListBucketsResponse.html[ListBucketsResponse]
is returned. Use this response object to retrieve the list of buckets.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.import.txt[]
----

*Code*

First create an S3Client.

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.region.txt[]
----

Make a List Buckets Request.

[source,java]
----
include::../../snippets/s3.java2.s3_bucket_ops.list_bucket.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3BucketOps.java[complete example]
on GitHub.

[[delete-bucket,delete-bucket.title]]
== Delete a bucket

Before you can delete an {S3} bucket, you must ensure that the bucket is empty or the service
will return an error. If you have a
{url-s3-dev}Versioning.html[versioned bucket], you must also delete any versioned objects that
are in the bucket.

[.topiclist-abbrev]
[[Topic List]]


[[delete-objects-in-a-bucket,delete-objects-in-a-bucket.title]]
=== Delete objects in a bucket

Build a
{v2javadocs}software/amazon/awssdk/services/s3/model/ListObjectsV2Request.html[ListObjectsV2Request]
and use the S3Client's `listObjects` method to retrieve the list of objects in the bucket. Then
use the `deleteObject` method on each object to delete it.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.import.txt[]
----

*Code*

First create an S3Client.

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.region.txt[]
----

Delete all objects in the bucket.

[source,java]
----
include::../../snippets/ss3.java2.bucket_deletion.delete_all_objects_bucket.txt[]
----

Delete the bucket.

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.delete_bucket.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3BucketDeletion.java[complete example]
on GitHub.

[[delete-an-empty-bucket,delete-an-empty-bucket.title]]
=== Delete an empty bucket

Build a
{v2javadocs}software/amazon/awssdk/services/s3/model/DeleteBucketRequest.html[DeleteBucketRequest]
with a bucket name and pass it to the S3Client's `deleteBucket` method.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.import.txt[]
----

*Code*

First create an S3Client.

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.region.txt[]
----

Delete the bucket.

[source,java]
----
include::../../snippets/s3.java2.bucket_deletion.delete_bucket.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3BucketDeletion.java[complete example]
on GitHub.