//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[examples-dynamodb-tables,examples-dynamodb-tables.title]]
= [[work-with-tables-in-ddb, Working with tables in DynamoDB]]Working with tables in {DDB}
:info_doctype: section
:info_title: Working with tables in {DDB}
:info_abstract: How to create, describe, modify (update) and delete {DDBlong} tables.
:info_keywordset: sdkjavav2code examples {DDB} tables

[abstract]
--
How to create, describe, modify (update) and delete {DDBlong} tables.
--

Tables are the containers for all items in a {DDB} database. Before you can add or remove data
from {DDB}, you must create a table.

For each table, you must define:

* A table _name_ that is unique for your account and region.
* A _primary key_ for which every value must be unique; no two items in your table can have the same primary key value.
+
A primary key can be __simple__, consisting of a single partition (HASH) key, or __composite__,
consisting of a partition and a sort (RANGE) key.
+
Each key value has an associated __data type__, enumerated by the
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ScalarAttributeType.html[ScalarAttributeType]
class. The key value can be binary (B), numeric (N), or a string (S). For more information, see
{url-ddb-dev}HowItWorks.NamingRulesDataTypes.html[Naming Rules and Data Types]
in the {guide-ddb-dev}.
* _Provisioned throughput_ are values that define the number of reserved read/write capacity units for the table.
+
NOTE: link:dynamodb/pricing/["pass:q[[.shared\]`DDBlong`] pricing", type="marketing"] is based on the provisioned
throughput values that you set on your tables, so reserve only as much capacity as you think
you'll need for your table.
+
Provisioned throughput for a table can be modified at any time, so you can adjust capacity as
your needs change.

[[dynamodb-create-table,dynamodb-create-table.title]]
== Create a table

Use the DynamoDbClient's `createTable` method to create a new {DDB} table. You need to construct
table attributes and a table schema, both of which are used to identify the primary key of your
table. You must also supply initial provisioned throughput values and a table name.

[NOTE]
====

If a table with the name you chose already exists, an
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/DynamoDbException.html[DynamoDbException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.create_table.import.txt[]
----


[[dynamodb-create-table-simple,dynamodb-create-table-simple.title]]
=== Create a table with a simple primary key

This code creates a table with a simple primary key ("`Name`").

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.create_table.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/CreateTable.java[complete example]
on GitHub.

[[dynamodb-create-table-composite,dynamodb-create-table-composite.title]]
=== Create a table with a composite primary key

Add another
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/AttributeDefinition.html[AttributeDefinition]
and {v2javadocs}software/amazon/awssdk/services/dynamodb/model/KeySchemaElement.html[KeySchemaElement]
to {v2javadocs}software/amazon/awssdk/services/dynamodb/model/CreateTableRequest.html[CreateTableRequest].

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.create_table_composite_key.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.create_table_composite_key.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/CreateTableCompositeKey.java[complete example]
on GitHub.

[[dynamodb-list-tables,dynamodb-list-tables.title]]
== List tables

You can list the tables in a particular region by calling the DynamoDbClient's `listTables` method.

[NOTE]
====

If the named table doesn't exist for your account and region, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.list_tables.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.list_tables.main.txt[]
----

By default, up to 100 tables are returned per call--use `lastEvaluatedTableName` on the returned
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ListTablesResponse.html[ListTablesResponse]
object to get the last table that was evaluated. You can use this value to start the listing
after the last returned value of the previous listing.

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/ListTables.java[complete example]
on GitHub.

[[dynamodb-describe-table,dynamodb-describe-table.title]]
== Describe (get information about) a table

Call the DynamoDbClient's `describeTable` method.

[NOTE]
====

If the named table doesn't exist for your account and region, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.describe_table.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.describe_table.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/DescribeTable.java[complete example]
on GitHub.

[[dynamodb-update-table,dynamodb-update-table.title]]
== Modify (update) a table

You can modify your table's provisioned throughput values at any time by calling the
DynamoDbClient's `updateTable` method.

[NOTE]
====

If the named table doesn't exist for your account and region, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.update_table.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.update_table.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/UpdateTable.java[complete example]
on GitHub.

[[dynamodb-delete-table,dynamodb-delete-table.title]]
== Delete a table

Call the DynamoDbClient's `deleteTable` method and pass it the table's name.

[NOTE]
====

If the named table doesn't exist for your account and region, a
{v2javadocs}software/amazon/awssdk/services/dynamodb/model/ResourceNotFoundException.html[ResourceNotFoundException]
is thrown.

====

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.delete_table.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.delete_table.main.txt[]
----

See the
{url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/DeleteTable.java[complete example]
on GitHub.

[[more-information,more-information.title]]
== More information

* {url-ddb-dev}GuidelinesForTables.html[Guidelines for Working with Tables] in the {guide-ddb-dev}
* {url-ddb-dev}WorkingWithTables.html[Working with Tables in {DDB}] in the {guide-ddb-dev}
