//!!NODE_ROOT <chapter>
include::../../includes.txt[]
:java-iamconsole-users: {url-console-domain}iam/home#/users
[."topic"]
[[get-started,get-started.title]]
= Get started with the SDK for Java
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Get started with the {sdkjavav2}
:info_titleabbrev: Quick start
:info_abstract: Quickly build your first Java application using the latest version of the {sdk-java}
:info_keywordset: start setup install get started java awssdk for java fast first running

[abstract]
--
Quickly build your first Java application using the latest version of the {sdk-java}
--

The {sdkjavav2} provides Java APIs for {AWSlong} ({AWS}). Using the SDK, you can build Java
applications that work with {S3}, {EC2}, {DDB}, and more.

This tutorial shows you how you can use https://maven.apache.org/[Apache Maven] to define
dependencies for the {sdk-java} and then write code that connects to {S3} to upload a file.

Follow these steps to complete this tutorial:


* xref:get-started-setup[Step 1: Set up for this tutorial,linkend=get-started-setup]
* xref:get-started-projectsetup[Step 2: Create the project,linkend=get-started-projectsetup]
* xref:get-started-code[Step 3: Write the code,linkend=get-started-code]
* xref:get-started-run[Step 4: Build and run the application,linkend=get-started-run]


[[get-started-setup,get-started-setup.title]]
== Step 1: Set up for this tutorial

Before you begin this tutorial, you need an active {AWS-account}, an {IAMlong} ({IAM}) user with a
programmatic access key and permissions to {S3}, and a Java development environment configured to
use that access key as credentials for {AWS}.

Follow these steps to set up for this tutorial:


* xref:get-started-setup-account[Create an {AWS-account},linkend=get-started-setup-account]
* xref:get-started-setup-user[Create an {IAM} user,linkend=get-started-setup-user]
* xref:get-started-setup-javamaven[Install Java and Apache Maven,linkend=get-started-setup-javamaven]
* xref:get-started-setup-credentials[Configure credentials,linkend=get-started-setup-credentials]


[[get-started-setup-account,get-started-setup-account.title]]
=== Create an account

If you do not have an {AWS-account}, visit
link:billing/signup["the pass:q[[.shared\]`AWSlong`] signup page", type="portal"]
and follow the on-screen prompts to create and activate a new account. For detailed instructions,
see link:premiumsupport/knowledge-center/create-and-activate-aws-account/["How do I create and activate a new pass:q[[.shared\]`AWS-account`]?", type="marketing"].

After you activate your new {AWS-account}, follow the instructions in
{java-admingroup}[Creating your first {IAM} admin user and group]
in the {guide-iam-user}. Use this account instead of the root account when accessing the {AWS}
Console. For more information, see
{link-iam-user}.

[[get-started-setup-user,get-started-setup-user.title]]
=== Create an IAM user

To complete this tutorial, you need to use credentials for an {IAM} user that has read and write
access to {S3}. To make requests to {AWSlong} using the {sdk-java}, create an access key to use
as credentials.

. Sign in to link:iam/["the pass:q[[.shared\]`IAM`] console", type="console"]
. In the navigation pane on the left, choose **Users**. Then choose **Add user**.
. Enter _TestSDK_ as the *User name* and select the *Programmatic access* checkbox. Choose **Next: Permissions**.
. Under **Set permissions**, select **Attach existing policies directly**.
. In the list of policies, select the checkbox for the *AmazonS3FullAccess* policy. Choose **Next: Tags**.
. Choose **Next: Review**. Then choose **Create user**.
. On the _Success_ screen, choose **Download .csv**.
+

The downloaded file contains the Access Key ID and the Secret Access Key for this tutorial. Treat
your Secret Access Key as a password; save in a trusted location and do not share it.
+
NOTE: You will *not* have another opportunity to download or copy the Secret Access Key.


[[get-started-setup-javamaven,get-started-setup-javamaven.title]]
=== Install Java and Apache Maven

Your development environment needs to have Java 8 or later and Apache Maven installed.


* For Java, use https://www.oracle.com/java/technologies/javase-downloads.html[Oracle Java SE Development Kit], link:corretto/["pass:q[[.shared\]`JDKlong`]", type="marketing"], https://developers.redhat.com/products/openjdk[Red Hat OpenJDK], or https://adoptopenjdk.net/[AdoptOpenJDK].
* For Maven, go to https://maven.apache.org/.


[[get-started-setup-credentials,get-started-setup-credentials.title]]
=== Configure credentials

Configure your development environment with your Access Key ID and the Secret Access Key. The
{sdk-java} uses this access key as credentials when your application makes requests to {AWSlong}.

. In a text editor, create a new file with the following code:
+
[source,xml]
----
[default]
aws_access_key_id = YOUR_AWS_ACCESS_KEY_ID
aws_secret_access_key = YOUR_AWS_SECRET_ACCESS_KEY
----
. In the text file you just created, replace _YOUR_AWS_ACCESS_KEY_ with your unique {AWS} access key ID, and replace _YOUR_AWS_SECRET_ACCESS_KEY_ with your unique {AWS} secret access key.
. Save the file without a file extension. Refer to the following table for the correct location and file name based on your operating system.
+
.{zwsp}

|===
|Operating system |File name

|Windows
|[path]``C:\Users\<yourUserName>\.aws\credentials``

|Linux, macOS, Unix
|[path]``~/.aws/credentials``
|===


[[get-started-projectsetup,get-started-projectsetup.title]]
== Step 2: Create the project

To create the project for this tutorial, you first create a Maven project. Next, you configure
your project with a dependency on {sdk-java} and for any {AWS-service} you use, for example {S3}.
Then you configure the Maven compiler to use Java 1.8.

. Open a terminal or command prompt window and navigate to a directory of your choice, for example, your Desktop or Home folder.
. Use the following command to create a new directory called [path]``myapp`` with a project configuration file ([path]``pom.xml``) and a basic Java class.
+
[source,sh]
----
mvn -B archetype:generate \
 -DarchetypeGroupId=org.apache.maven.archetypes \
 -DgroupId=com.example.myapp \
 -DartifactId=myapp
----

*To configure your project with dependencies for the {sdk-java} and {S3}, and to use Java 1.8*


* In the folder [path]``myapp`` that you created in the previous procedure, open the [path]``pom.xml`` file. Replace its contents with the following code, and then save your changes.
+
[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
 </properties>
 <groupId>com.example.myapp</groupId>
 <artifactId>myapp</artifactId>
 <packaging>jar</packaging>
 <version>1.0-SNAPSHOT</version>
 <name>myapp</name>
 <dependencyManagement>
  <dependencies>
   <dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>bom</artifactId>
    <version>2.16.60</version>
    <type>pom</type>
    <scope>import</scope>
   </dependency>
  </dependencies>
 </dependencyManagement>
 <dependencies>
  <dependency>
   <groupId>junit</groupId>
   <artifactId>junit</artifactId>
   <version>3.8.1</version>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>software.amazon.awssdk</groupId>
   <artifactId>s3</artifactId>
  </dependency>
 </dependencies>
 <build>
  <plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
     <source>8</source>
     <target>8</target>
    </configuration>
   </plugin>
  </plugins>
 </build>
</project>
----

The `dependencyManagement` section contains a dependency to the {sdk-java} and the `dependencies`
section has a dependency for {S3}. The Apache Maven Compiler Plugin is configured in the `build`
section to use Java 1.8.

[[get-started-code,get-started-code.title]]
== Step 3: Write the code

After the project has been created and configured, edit the project's default class `App` to use
the example code below.

The example class below creates a service client for {S3} and then uses it to upload a text file.
To create a service client for {S3}, instantiate an
{v2javadocs}software/amazon/awssdk/services/s3/S3Client.html[S3Client]
object using the static factory method ``builder``. To upload a file to {S3}, first build a
{v2javadocs}software/amazon/awssdk/services/s3/model/PutObjectRequest.html[PutObjectRequest]
object, supplying a bucket name and a key name. Then, call the S3Client's `putObject` method,
with a
{v2javadocs}software/amazon/awssdk/core/sync/RequestBody.html[RequestBody]
that contains the object content and the `PutObjectRequest` object.

. In your project folder [path]``myapp``, navigate to the directory [path]``src/main/java/com/example/myapp``. Open the [path]``App.java`` file.
. Replace its contents with the following code and save the file.
+
[source,java]
----
package com.example.myapp;

import java.io.IOException;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.model.CreateBucketConfiguration;
import software.amazon.awssdk.services.s3.model.CreateBucketRequest;
import software.amazon.awssdk.services.s3.model.DeleteBucketRequest;
import software.amazon.awssdk.services.s3.model.DeleteObjectRequest;
import software.amazon.awssdk.services.s3.model.HeadBucketRequest;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.services.s3.model.S3Exception;
import software.amazon.awssdk.services.s3.S3Client;


public class App {

  public static void main(String[] args) throws IOException {

    Region region = Region.US_WEST_2;
    S3Client s3 = S3Client.builder().region(region).build();

    String bucket = "bucket" + System.currentTimeMillis();
    String key = "key";

    tutorialSetup(s3, bucket, region);

    System.out.println("Uploading object...");

    s3.putObject(PutObjectRequest.builder().bucket(bucket).key(key)
            .build(),
        RequestBody.fromString("Testing with the {sdk-java}"));

    System.out.println("Upload complete");
    System.out.printf("%n");

    cleanUp(s3, bucket, key);

    System.out.println("Closing the connection to {S3}");
    s3.close();
    System.out.println("Connection closed");
    System.out.println("Exiting...");
  }

  public static void tutorialSetup(S3Client s3Client, String bucketName, Region region) {
    try {
      s3Client.createBucket(CreateBucketRequest
          .builder()
          .bucket(bucketName)
          .createBucketConfiguration(
              CreateBucketConfiguration.builder()
                  .locationConstraint(region.id())
                  .build())
          .build());
      System.out.println("Creating bucket: " + bucketName);
      s3Client.waiter().waitUntilBucketExists(HeadBucketRequest.builder()
          .bucket(bucketName)
          .build());
      System.out.println(bucketName +" is ready.");
      System.out.printf("%n");
    } catch (S3Exception e) {
      System.err.println(e.awsErrorDetails().errorMessage());
      System.exit(1);
    }
  }

  public static void cleanUp(S3Client s3Client, String bucketName, String keyName) {
    System.out.println("Cleaning up...");
    try {
      System.out.println("Deleting object: " + keyName);
      DeleteObjectRequest deleteObjectRequest = DeleteObjectRequest.builder().bucket(bucketName).key(keyName).build();
      s3Client.deleteObject(deleteObjectRequest);
      System.out.println(keyName +" has been deleted.");
      System.out.println("Deleting bucket: " + bucketName);
      DeleteBucketRequest deleteBucketRequest = DeleteBucketRequest.builder().bucket(bucketName).build();
      s3Client.deleteBucket(deleteBucketRequest);
      System.out.println(bucketName +" has been deleted.");
      System.out.printf("%n");
    } catch (S3Exception e) {
      System.err.println(e.awsErrorDetails().errorMessage());
      System.exit(1);
    }
    System.out.println("Cleanup complete");
    System.out.printf("%n");
  }
}
----


[[get-started-run,get-started-run.title]]
== Step 4: Build and run the application

After the project is created and contains the example class, build and run the application. To
view the uploaded file in the {S3} console, edit the code to remove the cleanup steps and then
rebuild the project.

. Open a terminal or command prompt window and navigate to your project directory [path]``myapp``.
. Use the following command to build your project:
+
[source,sh]
----
mvn package
----
. Open a terminal or command prompt window and navigate to your project directory [path]``myapp``.
. Use the following command to run the application.
+
[source,sh]
----
mvn exec:java -Dexec.mainClass="com.example.myapp.App"
----

When you run the application, it uploads a new a text file to a new bucket in {S3}. Afterward, it
will also delete the file and bucket.

. In [path]``App.java``, comment out the line `cleanUp(s3, bucket, key);` and save the file.
. Rebuild the project by running ``mvn package``.
. Upload the file by running `mvn exec:java -Dexec.mainClass="com.example.myapp.App"` again.
. Sign in to link:s3/["the S3 console", type="console"] to view the new file in the newly-created bucket.

After you view the file, clean up test resources by deleting the object and then deleting the
bucket.

[[get-started-success,get-started-success.title]]
=== Success!

If your Maven project built and ran without error, then congratulations! You have successfully
built your first Java application using the {sdk-java}.

[[cleanup,cleanup.title]]
=== Cleanup

To clean up the resources you created during this tutorial:


* In link:s3/["the S3 console", type="console"], delete any objects and any buckets created when you ran the application.
* In {java-iamconsole-users}[the {IAM} console], delete the _TestSDK_ user.
+

If you delete this user, also remove the contents of the [path]``credentials`` file you created during setup.
* Delete the project folder ([path]``myapp``).


[[get-started-next,get-started-next.title]]
== Next steps

Now that you have the basics down, you can learn about:


* xref:examples-s3[Working with {S3},linkend=examples-s3]
* xref:examples[Working with other {AWSlong},linkend=examples], such as xref:examples-dynamodb[{DDB},linkend=examples-dynamodb], xref:examples-ec2[{EC2},linkend=examples-ec2], and xref:examples-iam[{IAM},linkend=examples-iam]
* xref:using[Using the SDK,linkend=using]
* xref:security[Security for the {sdk-java},linkend=security]
