//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[http-configuration-crt,http-configuration-crt.title]]
= [[configuring-the-aws-crt-based-http-client, Configuring the CRT-based HTTP client]]Configuring the {AWS} CRT-based HTTP client
:info_doctype: section
:info_title: Configuring the {AWS} CRT-based HTTP client
:info_abstract: How to configure service clients to use the {AWS} Common Runtime as the HTTP client
:info_keywordset: sdk-javacrthttpclientserviceclientconfigureasync

[abstract]
--
How to configure service clients to use the {AWS} Common Runtime as the HTTP client
--

The {AWS} Common Runtime (CRT) HTTP client is a new HTTP client you can use with the {sdkjavav2}. The CRT-based HTTP client is an asynchronous, non-blocking HTTP client built on top of the Java bindings of the {url-github}awslabs/aws-crt-java[{AWS} Common Runtime]. You can use the CRT-based HTTP client to benefit from features such as improved performance, connection health checks, and post-quantum TLS support.

For asynchronous operations in the {sdkjavav2}, you can use Netty ({v2javadocs}software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.html[NettyNioAsyncHttpClient]) as the HTTP client or you can use the new {AWS} Common Runtime (CRT) HTTP client {v2javadocs}software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.html[AwsCrtAsyncHttpClient]. This topics shows you how to configure the {AWS} CRT-based HTTP client.

[[prerequisitescrt,prerequisitescrt.title]]
== Prerequisites

Before you can use use the {AWS} CRT client, you need to configure your project dependencies in your [path]``pom.xml`` or [path]``build.gradle`` file to do the following:



* Use version `2.14.13` or later of the {sdk-java}.
* Include version `2.14.13-PREVIEW` of the `artifactId```aws-crt-client``.

The following code example shows how to configure your project dependencies.

[source,xml]
----
<project>
  <dependencyManagement>
   <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>2.14.13</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
   </dependencies>
  </dependencyManagement>
  <dependencies>
   <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>aws-crt-client</artifactId>
      <version>2.14.13-PREVIEW</version>
   </dependency>
  </dependencies>
</project>
----


[[using-the-crt-based-http-client,using-the-crt-based-http-client.title]]
== Using the CRT-based HTTP client

You can use the CRT-based HTTP client for a specific service client, or you can create a single HTTP client to share across multiple service clients. These options are recommended for most use cases. Alternatively, you can set the CRT-based client as the default HTTP client for all asynchronous service clients and requests in your application.

The following code example shows how to use the CRT-based HTTP client for a specific service client.

[source,java]
----
S3AsyncClient.builder()
       .httpClientBuilder(AwsCrtAsyncHttpClient.builder()
                           .maxConcurrency(50))
       .build();
----

The following code example shows how to use the CRT-based HTTP client as a shared HTTP client.

[source,java]
----
SdkAsyncHttpClient crtClient = AwsCrtAsyncHttpClient.create()
S3AsyncClient.builder()
       .httpClient(crtClient)
       .build();
----

[NOTE]
====

Your application must manage the lifecycle of an HTTP client instantiated outside of a service client builder. (A `builder` is static factory method used by the {sdk-java} to connect to {AWSlong} such as {S3} and {AKlong}. For more information, see xref:creating-clients[Creating service clients,linkend=creating-clients].)

====

[[setting-the-crt-based-http-client-as-the-default,setting-the-crt-based-http-client-as-the-default.title]]
=== Setting the CRT-based HTTP client as the default

For asynchronous operations in the {sdkjavav2}, you can use Netty ({v2javadocs}software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.html[NettyNioAsyncHttpClient]) or the new {AWS} CRT-based HTTP client ({v2javadocs}software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.html[AwsCrtAsyncHttpClient]) as the default asynchronous HTTP client in the {sdkjavav2}.

Instead of using Netty as the asynchronous HTTP client, you can set the CRT-based HTTP client to be the default for your application. You can set this in your project's dependencies (for example, Maven [path]``pom.xml`` file) by explictly excluding Netty. Alternatively, you can set the default HTTP client via Java system property when you run your app or in your application code.

[[remove-netty-from-the-project-dependencies,remove-netty-from-the-project-dependencies.title]]
=== Remove Netty from the project dependencies

Refer to the following snippet of a Maven [path]``pom.xml`` file.

[source,xml]
----
<project>
  <dependencies>
   <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3</artifactId>
      <version>2.14.13</version>
      <exclusions>
         <exclusion>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>netty-nio-client</artifactId>
         </exclusion>
      </exclusions>
   </dependency>
   <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>aws-crt-client</artifactId>
      <version>2.14.13-PREVIEW</version>
   </dependency>
  </dependencies>
</project>
----


[[setting-via-java-system-property,setting-via-java-system-property.title]]
=== Setting via Java system property

To use the CRT-based HTTP client as the default HTTP for your application, you can set the Java system property `software.amazon.awssdk.http.async.service.impl` to a value of ``software.amazon.awssdk.http.crt.AwsCrtSdkHttpService``.

To set during application startup, run a command similar to the following.

[source,sh]
----
java app.jar -Dsoftware.amazon.awssdk.http.async.service.impl=\
software.amazon.awssdk.http.crt.AwsCrtSdkHttpService
----

Use the following code snippet to set in your application code.

[source,java]
----
System.setProperty("software.amazon.awssdk.http.async.service.impl",
"software.amazon.awssdk.http.crt.AwsCrtSdkHttpService");
----


[[configuring-the-crt-based-http-client,configuring-the-crt-based-http-client.title]]
==== Configuring the CRT-based HTTP client

With the CRT-based HTTP client with in the {sdk-java}, you can configure various settings including connection health checks and maximum idle time. You can also configure post-quantum TLS support when you make requests to {AWS} Key Management Service ({AKlong}).

[[connection-health-checks,connection-health-checks.title]]
== Connection health checks

You can configure connection health checks for the CRT-based HTTP client using the `connectionHealthChecks` method on the HTTP client builder. Refer to the following example code snippet and the {v2javadocs}software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.html[API documentation].

[source,java]
----
AwsCrtAsyncHttpClient.builder()
           .connectionHealthChecksConfiguration(
              b -> b.minThroughputInBytesPerSecond(32000L)
                 .allowableThroughputFailureInterval(Duration.ofSeconds(3)))
           .build();
----


[[post-quantum-tls-support,post-quantum-tls-support.title]]
== Post-quantum TLS support

You can configure the CRT-based HTTP client to use post-quantum TLS when your application makes requests to {AKlong}. Use the `tlsCipherPreference` method on the HTTP client builder. Refer to the following example code snippet and the {v2javadocs}software/amazon/awssdk/http/crtAwsCrtAsyncHttpClient.Builder.html[API documentation].

[source,java]
----
SdkAsyncHttpClient awsCrtHttpClient = AwsCrtAsyncHttpClient.builder()
                               .tlsCipherPreference(TlsCipherPreference.TLS_CIPHER_KMS_PQ_TLSv1_0_2019_06)
                               .build();
KmsAsyncClient kms = KmsAsyncClient.builder()
                  .httpClient(awsCrtHttpClient)
                  .build();
----