//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---sdk-amazonaws-com-java-api-latest-software-amazon-awssdk-ClientConfiguration-html-setLocalAddress-java-net-InetAddress-: {v2javadocs}software/amazon/awssdk/ClientConfiguration.html#setLocalAddress-java.net.InetAddress-
:https---sdk-amazonaws-com-java-api-latest-software-amazon-awssdk-core-retry-RetryPolicy-Builder-html-numRetries-java-lang-Integer-: {v2javadocs}software/amazon/awssdk/core/retry/RetryPolicy.Builder.html#numRetries-java.lang.Integer-
:https---sdk-amazonaws-com-java-api-latest-software-amazon-awssdk-http-SdkHttpConfigurationOption-html-CONNECTION-TIME-TO-LIVE-: {v2javadocs}software/amazon/awssdk/http/SdkHttpConfigurationOption.html#CONNECTION_TIME_TO_LIVE>
:https---sdk-amazonaws-com-java-api-latest-software-amazon-awssdk-core-client-config-ClientOverrideConfiguration-apiCallAttemptTimeout---html: {v2javadocs}software/amazon/awssdk/core/client/config/ClientOverrideConfiguration#apiCallAttemptTimeout--.html
[."topic"]
[[http-configuration,http-configuration.title]]
= HTTP configuration
:info_doctype: section
:info_title: HTTP configuration
:info_abstract: How to configure HTTP clients in the {sdk-java}.

[abstract]
--
How to configure HTTP clients in the {sdk-java}.
--

You can change the default configuration for HTTP clients in applications you build with the
{sdk-java}. This section discusses what HTTP clients for the {sdkjavav2} are available.

For asynchronous clients, you can use the
{v2javadocs}software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.html[NettyNioAsyncHttpClient]
or {v2javadocs}software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.html[AwsCrtAsyncHttpClient]. 
For more information, see
xref:http-configuration-netty[Configuring the Netty-based HTTP client,linkend=http-configuration-netty]
or xref:http-configuration-crt[Configuring the {AWS} CRT-based HTTP client,linkend=http-configuration-crt]. 
`NettyNioAsyncHttpClient` is the default asynchronous HTTP client shipped with the SDK.

For synchronous clients, you can use
{v2javadocs}software/amazon/awssdk/http/apache/ApacheHttpClient.html[ApacheHttpClient] 
or {v2javadocs}software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.html[UrlConnectionHttpClient]. 
For more information about Apache HTTPClient, see
https://hc.apache.org/httpcomponents-client-4.5.x/index.html[HttpClient Overview].
`ApacheHttpClient` is the default synchronous HTTP client shipped with the SDK.

For a full list of options you can set with these clients, see the
{v2javadocs}[{sdkjavav2} API Reference].

include::http-configuration-crt.adoc[leveloffset=+1]

include::http-configuration-netty.adoc[leveloffset=+1]
