//!!NODE_ROOT <section>
include::../../includes.txt[]
:java-defaultregionprovider: {url-doc-domain}sdk-for-java/v2/developer-guide/java-dg-region-selection.html#default-region-provider-chain
:java-oracle-time: https://docs.oracle.com/javase/8/docs/api/index.html?java/time.html
:java-oracle-urlconnection: https://docs.oracle.com/javase/8/docs/api/index.html?java/net/URLConnection.html
[."topic"]
[[lambda-optimize-starttime,lambda-optimize-starttime.title]]
= [[optimizing-cold-start-performance-for-lamlong, Optimizing cold start performance for lambda]]Optimizing cold start performance for {LAMlong}
:info_doctype: section
:info_title: Optimizing cold start performance for {LAMlong}
:info_abstract: How to minimize SDK startup time when using {sdk-java} with {LAMlong}.
:info_keywordset: sdk-javalambdastartupcoldstartfunctionsHTTPclientperformance

[abstract]
--
Howto minimize SDK startup time when using {sdk-java} with {LAMlong}.
--

Among the improvements in the {sdkjavav2} is the SDK cold startup time for Java functions in
{LAM}. This is the time it takes for a Java {LAM} function to start up and respond to its first
request.

Version 2.x includes three primary changes that contribute to this improvement:



* Use of {url-github}FasterXML/jackson-jr[jackson-jr], which is a serialization library that improves initialization time.
* Use of the {java-oracle-time}[java.time] libraries for date and time objects.
* Use of https://www.slf4j.org/[Slf4j] for a logging facade.

You can gain additional SDK startup time improvement by setting specific configuration values on
the client builder. They each save some time at startup by reducing the amount of information
your application needs to find for initialization.

In your client builder, specify a region, use Environment Variable credentials provider, and
specify UrlConnectionClient as the httpClient. See the code snippet below for an example.



* {java-defaultregionprovider}[The region lookup process] for the SDK takes time. By specifying a region, you can save up to 80ms of initialization time.
+
NOTE: By specifying an {AWS} region, the code will not run in other regions without modification.
* The process the SDK uses to look for credentials can take up to 90ms. By using the {v2javadocs}software/amazon/awssdk/auth/credentials/EnvironmentVariableCredentialsProvider.html[EnvironmentVariableCredentialsProvider]
+
NOTE: Using this credentials provider enables the code to be used in {LAM} functions, but may not work on {EC2} or other systems.
* Instantiation time for JDK's {java-oracle-urlconnection}[URLConnection] library is much lower than Apache HTTP Client or Netty. You can save up to 1 second by using this HTTP client.


[[example-client-configuration,example-client-configuration.title]]
== Example client configuration

[source,java]
----
S3Client client = S3Client.builder()
       .region(Region.US_WEST_2)
       .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
       .httpClient(UrlConnectionHttpClient.builder().build())
       .build();
----
