//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[migration-client-credentials,migration-client-credentials.title]]
= Credentials provider changes
:info_doctype: section
:info_title: Credentials provider changes
:info_abstract: Additional notes about changes to client credential configuration.

[abstract]
--
Additional notes about changes to client credential configuration.
--

[[client-credentials,client-credentials.title]]
== Credentials provider

This section provides a mapping of the name changes of credential provider classes and methods
between versions {v1ver} and {v2ver} of the {sdk-java}. The following also lists some of the key
differences in the way credentials are processed by the SDK in version {v2ver}:



* The default credentials provider loads system properties before environment variables in
version {v2ver}. See <<credentials,Using credentials>> for more information.
* The constructor method is replaced with the `create` or `builder` methods. 
+
====


[source,java]
----
DefaultCredentialsProvider.create();
----

====
* Asynchronous refresh is no longer set by default. You must specify it with the `builder` of the
credentials provider.
+
====


[source,java]
----
ContainerCredentialsProvider provider = ContainerCredentialsProvider.builder()
        		.asyncCredentialUpdateEnabled(true)
        		.build();
----

====
* You can specify a path to a custom profile file using the ``ProfileCredentialsProvier.builder()``. 
+
====


[source,java]
----
ProfileCredentialsProvider profile = ProfileCredentialsProvider.builder()
        		.profileFile(ProfileFile.builder().content(Paths.get("myProfileFile.file")).build())
        		.build();
----

====
* Profile file format has changed to more closely match the {CLI}. See
{url-cli-ug}cli-chap-getting-started.html[Configuring the {CLI}] in the _{guide-cli-ug}_ for
details.


[[credentials-changes-mapping,credentials-changes-mapping.title]]
== Credentials provider changes mapped between versions 1.x and 2.x

.Method name changes
[cols="1,1", options="header"]
|===
| {v1ver}
| {v2ver}

|

`AWSCredentialsProvider.getCredentials`
|

`AwsCredentialsProvider.resolveCredentials`

|

`DefaultAWSCredentialsProviderChain.getInstance`
|

Not Supported

|

`AWSCredentialsProvider.getInstance`
|

Not Supported

|

`AWSCredentialsProvider.refresh`
|

Not Supported
|===

.Environment variable name changes
[cols="1,1", options="header"]
|===
| {v1ver}
| {v2ver}

|

`AWS_ACCESS_KEY`
|

`AWS_ACCESS_KEY_ID`

|

`AWS_SECRET_KEY`
|

`AWS_SECRET_ACCESS_KEY`

|

`AWS_CREDENTIAL_PROFILES_FILE`
|

`AWS_SHARED_CREDENTIALS_FILE`
|===

.System property name changes
[cols="1,1", options="header"]
|===
| {v1ver}
| {v2ver}

|

`aws.secretKey`
|

`aws.secretAccessKey`

|

`com.amazonaws.sdk.disableEc2Metadata`
|

`aws.disableEc2Metadata`

|

`com.amazonaws.sdk.ec2MetadataServiceEndpointOverride`
|

`aws.ec2MetadataServiceEndpoint`
|===
