//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodbasync-src-main-java-com-example-dynamodbasync-AsyncPagination-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodbasync/src/main/java/com/example/dynamodbasync/AsyncPagination.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3ObjectOperations-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3ObjectOperations.java
[."topic"]
[[pagination,pagination.title]]
= [[retrieving-paginated-results, Retrieving paginated results]]Retrieving paginated results
:info_doctype: section
:info_title: Retrieving paginated results using the {sdkjavav2}
:info_titleabbrev: Pagination
:info_abstract: How to use stream to get automatic pagination in {sdkjavav2}.
:info_keywordset: sdkjavav2S3code examplesasync paginationlistObjectsV2PaginatorlistTablesPaginatorpaginate

[abstract]
--
How to use stream to get automatic pagination in {sdkjavav2}.
--

Many {AWS} operations return paginated results when the response object is too large to return in a single response. In the {sdk-java} 1.0, the response contained a token you had to use to retrieve the next page of results. New in the {sdkjavav2} are autopagination methods that make multiple service calls to get the next page of results for you automatically. You only have to write code that processes the results. Additionally both types of methods have synchronous and asynchronous versions. See examples-asynchronous for more detail about asynchronous clients.

The following examples use {S3} and {DDBlong} operations to demonstrate the various methods of retrieving your data from paginated responses.

[NOTE]
====

These code snippets assume that you understand the material in basics, and have configured default {AWS} credentials using the information in setup-credentials.

====

[[synchronous-pagination,synchronous-pagination.title]]
== Synchronous pagination

These examples use the synchronous pagination methods for listing objects in an {S3} bucket.

[[iterate-pages,iterate-pages.title]]
=== Iterate over pages

Build a {v2javadocs}software/amazon/awssdk/services/s3/model/ListObjectsV2Request.html[ListObjectsV2Request] and provide a bucket name. Optionally you can provide the maximum number of keys to retrieve at one time. Pass it to the S3Client's `listObjectsV2Paginator` method. This method returns a {v2javadocs}software/amazon/awssdk/services/s3/paginators/ListObjectsV2Iterable.html[ListObjectsV2Iterable] object, which is an `Iterable` of the {v2javadocs}software/amazon/awssdk/services/s3/model/ListObjectsV2Response.html[ListObjectsV2Response] class.

The first example demonstrates using the paginator object to iterate through all the response pages with the `stream` method. You can directly stream over the response pages, convert the response stream to a stream of {v2javadocs}software/amazon/awssdk/services/s3/model/S3Object.html[S3Object] content, and then process the content of the {S3} object.

*Imports*

[source,java]
----
include::../../snippets/s3.java2.s3_object_operations.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/s3.java2.s3_object_operations.iterative.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3ObjectOperations-java}[complete example] on GitHub.

[[iterate-objects,iterate-objects.title]]
=== Iterate over objects

The following examples show ways to iterate over the objects returned in the response instead of the pages of the response.

[[use-a-stream,use-a-stream.title]]
==== Use a stream

Use the `stream` method on the response content to iterate over the paginated item collection.

*Code*

[source,java]
----
include::../../snippets/s3.java2.s3_object_operations.stream.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3ObjectOperations-java}[complete example] on GitHub.

[[for-loop,for-loop.title]]
==== Use a for loop

Use a standard `for` loop to iterate through the contents of the response.

*Code*

[source,java]
----
include::../../snippets/s3.java2.s3_object_operations.forloop.txt[']
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3ObjectOperations-java}[complete example] on GitHub.

[[manual-pagination,manual-pagination.title]]
=== Manual pagination

If your use case requires it, manual pagination is still available. Use the next token in the response object for the subsequent requests. Here's an example using a `while` loop.

*Code*

[source,java]
----
include::../../snippets/s3.java2.s3_object_operations.pagination.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3ObjectOperations-java}[complete example] on GitHub.

[[asynchronous-pagination,asynchronous-pagination.title]]
== Asynchronous pagination

These examples use the asynchronous pagination methods for listing tables in {DDB}. A manual pagination example is available in the basics-async topic.

[[iterate-pages-async,iterate-pages-async.title]]
=== Iterate over pages of table names

First, create an asynchronous {DDB} client. Then, call the `listTablesPaginator` method to get a {v2javadocs}software/amazon/awssdk/services/dynamodb/paginators/ListTablesPublisher.html[ListTablesPublisher]. This is an implementation of the reactive streams Publisher interface. To learn more about the reactive streams model, see the {url-github}reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md[Reactive Streams Github repo].

Call the `subscribe` method on the {v2javadocs}software/amazon/awssdk/services/dynamodb/paginators/ListTablesPublisher.html[ListTablesPublisher] and pass a subscriber implementation. In this example, the subscriber has an `onNext` method that requests one item at a time from the publisher. This is the method that is called repeatedly until all pages are retrieved. The `onSubscribe` method calls the `Subscription.request` method to initiate requests for data from the publisher. This method must be called to start getting data from the publisher. The `onError` method is triggered if an error occurs while retrieving data. Finally, the `onComplete` method is called when all pages have been requested.

[[use-a-subscriber,use-a-subscriber.title]]
==== Use a subscriber

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.import.txt[]
----

*Code*

First create an async client

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.pagesclient.txt[]
----

Then use Subscriber to get results.

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.pagessubscribe.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodbasync-src-main-java-com-example-dynamodbasync-AsyncPagination-java}[complete example] on GitHub.

[[id1pagination,id1pagination.title]]
==== Use a for loop

Use a `for` loop to iterate through the pages for simple use cases when creating a new subscriber might be too much overhead. The response publisher object has a `forEach` helper method for this purpose.

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.pagesforeach.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodbasync-src-main-java-com-example-dynamodbasync-AsyncPagination-java}[complete example] on GitHub.

[[iterate-objects-async,iterate-objects-async.title]]
=== Iterate over table names

The following examples show ways to iterate over the objects returned in the response instead of the pages of the response. Similar to the synchronous result, the asynchronous result class has a method to interact with the underlying item collection. The return type of the convenience method is a publisher that can be used to request items across all pages.

[[id2,id2.title]]
==== Use a subscriber

*Code*

First create an async client

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.asyncclient.txt[]
----

Then use Subscriber to get results.

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.subscriber.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodbasync-src-main-java-com-example-dynamodbasync-AsyncPagination-java}[complete example] on GitHub.

[[for-loop-async,for-loop-async.title]]
==== Use a for loop

Use the `forEach` convenience method to iterate through the results.

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.foreach.txt[]
----

See the {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodbasync-src-main-java-com-example-dynamodbasync-AsyncPagination-java}[complete example] on GitHub.

[[use-third-party-library,use-third-party-library.title]]
=== Use third-party library

You can use other third party libraries instead of implementing a custom subscriber. This example demonstrates using the RxJava implementation but any library that implements the reactive stream interfaces can be used. See the {url-github}ReactiveX/RxJava/wiki[RxJava wiki page on Github] for more information on that library.

To use the library, add it as a dependency. If using Maven, the example shows the POM snippet to use.

*POM Entry*

[source,xml]
----
include::../../examples/dynamodb/pom.xml[lines=46..50]
----

*Imports*

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.import.txt[]
----

*Code*

[source,java]
----
include::../../snippets/dynamodb.java2.async_pagination.async.txt[]
----
