//!!NODE_ROOT <section>

include::../../includes.txt[]
[."topic"]
[[security-data-protection,security-data-protection.title]]
= [[data-protection-in-sdk-java-2-x, Data protection in SDK for Java]]Data protection in {sdkjavav2}
:info_doctype: section
:info_title: Data protection in {sdkjavav2}
:info_titleabbrev: Data protection
:info_abstract: Learn how the {AWS} shared responsibility model applies to data protection in this {AWS} product or service.

[abstract]
--
Learn how the {AWS} shared responsibility model applies to data protection in this {AWS} product or service.
--

The link:compliance/shared-responsibility-model["shared responsibility model", type="marketing"]
applies to data protection in this {AWS} product or service. As described in this model, {AWS} is
responsible for protecting the global infrastructure that runs all of the {AWS} Cloud. You are
responsible for maintaining control over your content that is hosted on this infrastructure. This
content includes the security configuration and management tasks for the pass:q[[.shared\]`AWS`]
services that you use. For more information about data privacy, see the
link:compliance/data-privacy-faq["Data Privacy FAQ", type="marketing"]. For information about data protection in Europe, see the link:security/the-aws-shared-responsibility-model-and-gdpr["pass:q[[.shared\]`AWS`] Shared Responsibility Model and GDPR", type="blog"] blog post on the {AWS} Security Blog.

For data protection purposes, we recommend that you protect {AWS-account} credentials and set up individual user accounts with {IAMlong} ({IAM}). That way each user is given only the permissions necessary to fulfill their job duties. We also recommend that you secure your data in the following ways:



* Use multi-factor authentication (MFA) with each account.
* Use SSL/TLS to communicate with {AWS} resources. We recommend TLS 1.2 or later.
* Set up API and user activity logging with {CTlong}.
* Use {AWS} encryption solutions, with all default security controls within {AWS-services}.
* Use advanced managed security services such as Amazon Macie, which assists in discovering and securing personal data that is stored in {S3}.
* If you require FIPS 140-2 validated cryptographic modules when accessing {AWS} through a command line interface or an API, use a FIPS endpoint. For more information about the available FIPS endpoints, see link:compliance/fips["Federal Information Processing Standard (FIPS) 140-2", type="marketing"].

We strongly recommend that you never put sensitive identifying information, such as your customers' account numbers, into free-form fields such as a *Name* field. This includes when you work with this {AWS} product or service or other {AWS-services} using the console, API, {CLI}, or {AWS} SDKs. Any data that you enter into this {AWS} product or service or other services might get picked up for inclusion in diagnostic logs. When you provide a URL to an external server, don't include credentials information in the URL to validate your request to that server.