//!!NODE_ROOT <chapter>
include::../../includes.txt[]
:java-security-dontuseroot: IAM/latest/UserGuide/best-practices.html#lock-away-credentials
:java-security-keys: general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys
[."topic"]
[[setup,setup.title]]
= [[setting-up-the-sdk-java-2-x, Setting up the SDK for Java]]Setting up the {sdkjavav2}
:info_doctype: chapter
:info_title: Setting up the {sdkjavav2}
:info_titleabbrev: Setting up

The {sdkjavav2} provides Java APIs for {AWSlong} ({AWS}). Using the SDK, you can build Java
applications that work with {S3}, {EC2}, {DDB}, and more.

This section provides information about how to set up your development environment and projects
to use the latest version (2.x) of the {sdk-java}.

[[setup-overview,setup-overview.title]]
== Overview

To make requests to {AWS} using the {sdk-java}, you need the following:

* An active {AWS-account}
* An {IAMlong} ({IAM}) user with:

** A programmatic access key
** Permissions to the {AWS} resources you'll access using your application
* A development environment with:

** Your access key configured as credentials for {AWS}
** Java 8 or later
** A build automation tool

[[setup-awsaccount,setup-awsaccount.title]]
== Create an account

If you do not have an {AWS-account}, visit
link:billing/signup["the pass:q[[.shared\]`AWSlong`] signup page", type="portal"]
and follow the on-screen prompts to create and activate a new account.

For more detailed instructions, see
link:premiumsupport/knowledge-center/create-and-activate-aws-account/["How do I create and activate a new pass:q[[.shared\]`AWS-account`]?", type="marketing"].

After you activate your new {AWS-account}, follow the instructions in
{java-admingroup}[Creating your first IAM admin user and group]
in the
{link-iam-user}.
Use this account instead of the root account when accessing the {console}.
For more information, see
link:IAM/latest/UserGuide/best-practices.html#lock-away-credentials["Security best practices in IAM", type="documentation"]]
in the
{link-iam-user}.


[[setup-iamuser,setup-iamuser.title]]
== Create an IAM user and programmatic access key

To use the {sdk-java} to access {AWS-services}, you need an {AWS-account} and {AWS} credentials. To
increase the security of your {AWS-account}, for access credentials, we recommend that you use an
{IAM} user instead of your {AWS-account} credentials.

[NOTE]
====
For an overview of {IAM} users and why they are important for the security of your account, see
link:general/latest/gr/aws-security-credentials.html["pass:q[[.shared\]`AWS`] security credentials", type="documentation"]
in the {AWS-GEN-REF-long}.
====

For instructions on creating an access key for an existing {IAM} user, see
link:general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys["Programmatic access", type="documentation"] in the
{link-iam-user}.

. Go to the link:iam/home["pass:q[[.shared\]`IAM`] console", type="console"] (you may need to sign in to {AWS} first).
. Click *Users* in the sidebar to view your {IAM} users.
. If you don't have any {IAM} users set up, click *Create New Users* to create one.
. Select the {IAM} user in the list that you'll use to access {AWS}.
. Open the *Security Credentials* tab, and click **Create Access Key**.
NOTE: You can have a maximum of two active access keys for any given {IAM} user. If your {IAM} user has two access keys already, then you'll need to delete one of them before creating a new key.
. On the resulting dialog box, click the *Download Credentials* button to download the credential file to your computer, or click *Show User Security Credentials* to view the {IAM} user's access key ID and secret access key (which you can copy and paste).

IMPORTANT: There is no way to obtain the secret access key once you close the dialog box. You
can, however, delete its associated access key ID and create a new one.

[[setup-credentials,setup-credentials.title]]
== Set default credentials and Region

To make requests to {AWS} using the {sdk-java}, you must use cryptographically-signed credentials
issued by {AWS}. With {AWS} SDKs and Tools like the {sdk-java}, you use a programmatic access key,
consisting of an Access Key ID and and a Secret Access Key, as credentials. You should set your
credentials as the default credentials for accessing {AWS} with your application.

If you already have an {IAM} account created, see
xref:setup-iamuser[Create an {IAM} user and programmatic access key,linkend=setup-iamuser]
for instructions on creating a programmatic access key.

You should also set a default {AWS-Region} for accessing {AWS} with your application. Some
operations require a Region to be set. For the best network performance, you can select a Region
that is geographically near to you or your customers.

The most common way to set the default credentials and {AWS-Region} is to use the shared
[path]``config`` and [path]``credentials`` files. You can also set the default credentials and
Region using environment variables, using Java system properties or, for your applications
running on {EC2}, using
link:java/api/latest/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.html["ContainerCredentialsProvider", type="api"] or
{v2javadocs}software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.html[InstanceProfileCredentialsProvider].

[[setting-the-default-credentials,setting-the-default-credentials.title]]
=== Setting the default credentials

Select one of these options to set the default credentials:

* Set credentials in the {AWS} credentials profile file on your local system, located at:

** [path]``~/.aws/credentials`` on Linux, macOS, or Unix
** [path]``C:\Users\USERNAME\.aws\credentials`` on Windows

This file should contain lines in the following format:

[source,cfg]
----
[default]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
----

Substitute your own {AWS} credentials values for the values _your_access_key_id_ and
__your_secret_access_key__.

* Set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables.

To set these variables on Linux, macOS, or Unix, use **``export``**:

[source,sh]
----
export AWS_ACCESS_KEY_ID=your_access_key_id
export AWS_SECRET_ACCESS_KEY=your_secret_access_key
----

To set these variables on Windows, use **``set``**:

[source,bat]
----
set AWS_ACCESS_KEY_ID=your_access_key_id
set AWS_SECRET_ACCESS_KEY=your_secret_access_key
----

* For an {EC2} instance, specify an {IAM} role and then give your {EC2} instance access to that role. See {url-ec2-user}iam-roles-for-amazon-ec2.html[{IAM} Roles for {EC2}] in the {guide-ec2-user} for a detailed discussion about how this works.

* Set the `aws.accessKeyId` and `aws.secretAccessKey` Java system properties.

[source,sh]
----
java app.jar -Daws.accessKeyId=\
"your_access_key_id" \
-Daws.secretAccessKey=\
"your_secret_access_key"
----

[[setting-the-default-aws-region,setting-the-default-aws-region.title]]
=== Setting the default Region

Select one of these options to set the default Region:

* Set the {AWS-Region} in the {AWS} config file on your local system, located at:

** ~/.aws/config on Linux, macOS, or Unix
** C:\Users\USERNAME\.aws\config on Windows

This file should contain lines in the following format:

[source,cfg]
----
[default]
region = your_aws_region
----

Substitute your desired {AWS-Region} (for example, "`{region_api_default}`") for __your_aws_region__.

* Set the `AWS_REGION` environment variable.

On Linux, macOS, or Unix, use **``export``**:

[source,sh]
----
export AWS_REGION=your_aws_region
----

On Windows, use **``set``**:

[source,bat]
----
set AWS_REGION=your_aws_region
----

Where _your_aws_region_ is the desired {AWS-Region} name.

For additional information about setting credentials and Region, see
link:sdkref/latest/guide/creds-config-files.html["The .aws/credentials and .aws/config files", type="documentation"],
link:sdkref/latest/guide/setting-global-region.html["pass:q[[.shared\]`AWS-Region`]", type="documentation"], and
link:sdkref/latest/guide/environment-variables.html["Using environment variables", type="documentation"] in the
link:sdkref/latest/guide["pass:q[[.shared\]`AWS`] SDKs and Tools Reference Guide", type="documentation"].

[[setup-envtools,setup-envtools.title]]
== Install Java and a build tool

Your development environment needs the following:

* Java 8 or later. The {sdk-java} works with the https://www.oracle.com/java/technologies/javase-downloads.html[Oracle Java SE Development Kit] and with distributions of Open Java Development Kit (OpenJDK) such as link:corretto/["pass:q[[.shared\]`JDKlong`]", type="marketing"], https://developers.redhat.com/products/openjdk[Red Hat OpenJDK], and https://adoptopenjdk.net/[AdoptOpenJDK].
* A build tool or IDE that supports Maven Central such as Apache Maven, Gradle, or IntelliJ.

** For information about how to install and use Maven, see http://maven.apache.org/.
** For information about how to install and use Gradle, see https://gradle.org/.
** For information about how to install and use IntelliJ IDEA, see https://www.jetbrains.com/idea/.

[[setup-nextsteps,setup-nextsteps.title]]
== Next steps

Once you have your {AWS-account} and development environment set up, create a Java project using
your preferred build tool. Import
https://mvnrepository.com/artifact/software.amazon.awssdk/bom/latest[the Maven bill of materials (BOM) for the {sdkjavav2} from Maven Central],
``software.amazon.awssdk``. Then add dependendies for the services you'll use in your application.

Example Maven [path]``pom.xml`` file:

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
 </properties>
 <groupId>com.example.myapp</groupId>
 <artifactId>myapp</artifactId>
 <packaging>jar</packaging>
 <version>1.0-SNAPSHOT</version>
 <name>myapp</name>
 <dependencyManagement>
  <dependencies>
   <dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>bom</artifactId>
    <version>2.15.0</version>
    <type>pom</type>
    <scope>import</scope>
   </dependency>
  </dependencies>
 </dependencyManagement>
 <dependencies>
  <dependency>
   <groupId>junit</groupId>
   <artifactId>junit</artifactId>
   <version>3.8.1</version>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>software.amazon.awssdk</groupId>
   <artifactId>dynamodb</artifactId>
  </dependency>
  <dependency>
   <groupId>software.amazon.awssdk</groupId>
   <artifactId>iam</artifactId>
  </dependency>
  <dependency>
   <groupId>software.amazon.awssdk</groupId>
   <artifactId>kinesis</artifactId>
  </dependency>
  <dependency>
   <groupId>software.amazon.awssdk</groupId>
   <artifactId>s3</artifactId>
  </dependency>
 </dependencies>
 <build>
  <plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
     <source>8</source>
     <target>8</target>
    </configuration>
   </plugin>
  </plugins>
 </build>
</project>
----

Example [path]``build.gradle`` file:

[source,groovy]
----
group 'com.example.myapp'
version '1.0'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
 mavenCentral()
}

dependencies {
 implementation platform('software.amazon.awssdk:bom:2.15.0')
 implementation 'software.amazon.awssdk:dynamodb'
 implementation 'software.amazon.awssdk:iam'
 implementation 'software.amazon.awssdk:kinesis'
 implementation 'software.amazon.awssdk:s3'
 testImplementation group: 'junit', name: 'junit', version: '4.11'
}
----

For more information, see
xref:setup-project-maven[Setting up an Apache Maven project,linkend=setup-project-maven] or
xref:setup-project-gradle[Setting up a Gradle project,linkend=setup-project-gradle].


include::setup-project-maven.adoc[leveloffset=+1]


include::setup-project-gradle.adoc[leveloffset=+1]


include::setup-project-graalvm.adoc[leveloffset=+1]


include::setup-additional.adoc[leveloffset=+1]


include::migration.adoc[leveloffset=+1]

