//!!NODE_ROOT <section>

include::../../includes.txt[]
[."topic"]
[[setup-project-gradle,setup-project-gradle.title]]
= [[setting-up-a-gradle-project, Setting up a Gradle project]]Setting up a Gradle project
:info_doctype: section
:info_title: Setting up a Gradle project
:info_abstract: How to use Gradle to set up your {sdk-java} v2 project
:info_keywordset: sdk-javav2GradleBOMinstalldownloadsetup

[abstract]
--
Howto use Gradle to set up your {sdk-java} v2 project
--

You can use https://gradle.org/[Gradle] to set up and build {sdk-java} projects.

To manage SDK dependencies for your Gradle project, import the Maven bill of materials (BOM) for the {sdk-java} into the [path]``build.gradle`` file.

[NOTE]
====

In the following examples, replace _2.15.0_ in the [path]``build.gradle`` file with the latest version of the {sdk-java} v2. Find the latest version in the {v2javadocs}[{sdk-java} API Reference version 2.x].

====
. Add the BOM to the _dependencies_ section of the file.
+
[source,groovy]
----
...
dependencies {
 implementation platform('software.amazon.awssdk:bom:2.15.0')

 // Declare individual SDK dependencies without version
 ...
}
----
. Specify the SDK modules to use in the _dependencies_ section. For example, the following includes a dependency for {AKlong}.
+
[source,groovy]
----
...
dependencies {
 ...
 implementation 'software.amazon.awssdk:kinesis'
 ...
}
----

Gradle automatically resolves the correct version of your SDK dependencies by using the information from the BOM.

The following is an example of a complete [path]``build.gradle`` file that includes a dependency for {AK}.

[source,groovy]
----
group 'aws.test'
version '1.0'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
 mavenCentral()
}

dependencies {
 implementation platform('software.amazon.awssdk:bom:2.15.0')
 implementation 'software.amazon.awssdk:kinesis'
 testImplementation group: 'junit', name: 'junit', version: '4.11'
}
----

[NOTE]
====

In the previous example, replace the dependency for {AK} with the dependencies of the {AWS-services} you will use in your project. The modules (dependencies) that are managed by the {sdk-java} BOM are listed on Maven central repository (https://mvnrepository.com/artifact/software.amazon.awssdk/bom/latest).

====

For more information about specifying SDK dependencies by using the BOM, see xref:setup-project-maven[Setting up an Apache Maven project,linkend=setup-project-maven].