//!!NODE_ROOT <section>
include::../../includes.txt[]
[."topic"]
[[setup-additional,setup-additional.title]]
= [[additional-setup-information, Additional setup information]]Additional setup information
:info_doctype: section
:info_title: Additional setup information
:info_abstract: Additional information on setting up for the {sdkjavav2}
:info_keywordset: profile credentials maven install setup configure sdk project application

[abstract]
--
Additional information on setting up for the {sdkjavav2}
--

This topic supplements the information in xref:setup[Setting up the {sdkjavav2},linkend=setup].

[[setup-additional-credentials,setup-additional-credentials.title]]
== Set up credentials profiles

You can use more than one set of credentials in your application by setting up additional
credentials profiles. Like the `[default]` profile, you can set up custom profiles to use
programmatic access keys as credentials or to use temporary credentials.

To configure your own credentials profiles, use the shared [path]``credentials`` and
[path]``config`` files. See the snippets below for example usage.

*A profile,*__cloudwatch_metrics__**, configured in the**[path]``credentials``**file to use a
programmatic access key as credentials:**

[source,xml]
----
[cloudwatch_metrics]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
region = us-east-2
----

A profile, __devuser__, configured in the [path]``config`` file to use temporary credentials by
assuming a role based on an Amazon Resource Name (ARN).

[source,xml]
----
[profile devuser]
role_arn = {region-arn}iam::123456789012:role/developers
source_profile = dev-user
region = {region_api_default}
output = json
----

A profile, __user1__, configured in the [path]``credentials`` file to use {SSOlong} (SSO) for
credentials.

[source,xml]
----
[user1]
sso_start_url = https://my-sso-portal.awsapps.com/start
sso_region = us-east-1
sso_account_id = 123456789011
sso_role_name = readOnly
region = {region_api_default}
----

For additional information about configuring the shared [path]``credentials`` and
[path]``config`` files, see:



* xref:setup-credentials[Set default credentials and Region,linkend=setup-credentials]
* link:sdkref/latest/guide/file-format.html#file-format-example["Example config and credentials files", type="documentation"]
* link:sdkref/latest/guide/creds-config-files.html["The .aws/credentials and .aws/config files", type="documentation"]
* link:sdkref/latest/guide/usage-examples-role_from_user.html["Credentials for an pass:q[[.shared\]`IAM`] role assumed as an pass:q[[.shared\]`IAM`] user", type="documentation"]


[[set-an-alternate-credentials-file-location,set-an-alternate-credentials-file-location.title]]
=== Set an alternate credentials file location

By default, the {sdk-java} looks for the [path]``credentials`` file at [path]``~/.aws/credentials``. To customize the location of the shared [path]``credentials`` file, set the `AWS_SHARED_CREDENTIALS_FILE` environment variable to an alternate location.

To set this variable on Linux, macOS, or Unix, use ``export``:

[source,sh]
----
export AWS_SHARED_CREDENTIALS_FILE=path/to/credentials_file
----

To set this variable on Windows, use ``set``:

[source,sh]
----
set AWS_SHARED_CREDENTIALS_FILE=path/to/credentials_file
----
