//!!NODE_ROOT <section>
:https---www-graalvm-org-reference-manual-native-image--install-native-image: https://www.graalvm.org/reference-manual/native-image/#install-native-image

include::../../includes.txt[]
[."topic"]
[[setup-project-graalvm,setup-project-graalvm.title]]
= [[setting-up-a-graalvm-native-image-project-for-the-sdk-java, Setting up a GraalVM Native Image project for the SDK for Java]]Setting up a GraalVM Native Image project for the {sdk-java}
:info_doctype: section
:info_title: Setting up a GraalVM Native Image project for the {sdk-java}
:info_titleabbrev: Setting up a GraalVM Native Image project
:info_abstract: Set up a Maven project that generates a GraalVM native image.
:info_keywordset: sdk-java,setup, native image, graalvm, maven, project

[abstract]
--
Set up a Maven project that generates a GraalVM native image.
--

With versions 2.16.1 and later, the {sdk-java} provides out-of-the-box support for GraalVM Native Image applications. Use the `archetype-app-quickstart` Maven archetype to set up a project with built-in native image support.

[[setup-graalvmnativeimage-prereq,setup-graalvmnativeimage-prereq.title]]
== Prerequisites

* Complete the steps in xref:setup[Setting up the {sdkjavav2},linkend=setup].
* Install {https---www-graalvm-org-reference-manual-native-image--install-native-image}[GraalVM Native Image].


[[setup-graalvmnativeimage-project,setup-graalvmnativeimage-project.title]]
== Create a project using the archetype

To create a Maven project with built-in native image support, in a terminal or command prompt window, use the following command.

[NOTE]
====

Replace _com.example.mynativeimageapp_ with the full package namespace of your application. Also replace _mynativeimageapp_ with your project name. This becomes the name of the directory for your project.

====

[source,sh]
----
mvn archetype:generate \
    -DarchetypeGroupId=software.amazon.awssdk \
    -DarchetypeArtifactId=archetype-app-quickstart \
    -DarchetypeVersion=2.16.1 \
    -DnativeImage=true \
    -DhttpClient=apache-client \
    -Dservice=s3 \
    -DgroupId=com.example.mynativeimageapp \
    -DartifactId=mynativeimageapp \
    -DinteractiveMode=false
----

This command creates a Maven project configured with dependencies for the {sdk-java}, {S3}, and the `ApacheHttpClient` HTTP client. It also includes a dependency for the https://www.graalvm.org/reference-manual/native-image/NativeImageMavenPlugin/[GraalVM Native Image Maven plugin], so that you can build native images using Maven.

To include dependencies for a different {AWSlong}, set the value of the `-Dservice` parameter to the artifict ID of that service. For example, __dynamodb__, __iam__, __pinpoint__, etc. For a complete list of artifact IDs, see the list of managed dependencies for https://mvnrepository.com/artifact/software.amazon.awssdk/bom/latest[software.amazon.awssdk on Maven Central].

To use an asynchronous HTTP client, set the `-DhttpClient` parameter to ``netty-nio-client``. To use `UrlConnectionHttpClient` as the synchronous HTTP client instead of ``apache-client``, set the `-DhttpClient` parameter to ``url-connection-client``.

[[build-graalvmnativeimage-project,build-graalvmnativeimage-project.title]]
== Build a native image

After you create the project, run the following command from your project directory, for example, [path]``mynativeimageapp``:

[source,sh]
----
mvn package -P native-image
----

This creates a native image application in the [path]``target`` directory, for example, [path]``target/mynativeimageapp``.