//!!NODE_ROOT <section>
include::../../includes.txt[]
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3BucketOps-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3BucketOps.java
:https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodb-src-main-java-com-example-dynamodb-CreateTable-java: {url-awsdocs-github}aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/CreateTable.java
[."topic"]
[[waiters,waiters.title]]
= [[using-waiters, Using waiters]]Using waiters
:info_doctype: section
:info_title: Using waiters in the {sdkjavav2}
:info_titleabbrev: Waiters
:info_abstract: How to poll for {AWS} resource states using the waiters utility for the {sdk-java} v2
:info_keywordset: sdk-javawaiterspollingstateresourceserviceclient

[abstract]
--
How to poll for {AWS} resource states using the waiters utility for the {sdk-java} v2
--

The waiters utility of the {sdkjavav2} enables you to validate that {AWS} resources are in a specified state before performing operations on those resources.

A _waiter_ is an abstraction used to poll {AWS} resources, such as {DDB} tables or {S3} buckets, until a desired state is reached (or until a determination is made that the resource won't ever reach the desired state). Instead of writing logic to continuously poll your {AWS} resources, which can be cumbersome and error-prone, you can use waiters to poll a resource and have your code continue to run after the resource is ready.

[[prerequisiteswaiters,prerequisiteswaiters.title]]
== Prerequisites

Before you can use waiters in a project with the {sdk-java}, you must complete the steps in xref:setup[Setting up the {sdkjavav2},linkend=setup].

You must also configure your project dependencies (for example, in your [path]``pom.xml`` or [path]``build.gradle`` file) to use version `2.15.0` or later of the {sdk-java}.

For example:

[source,xml]
----
<project>
  <dependencyManagement>
   <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>2.15.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
   </dependencies>
  </dependencyManagement>
</project>
----


[[id1waiters,id1waiters.title]]
== Using waiters

To instantiate a waiters object, first create a service client. Set the service client's `waiter()` method as the value of the waiter object. Once the waiter instance exists, set its response options to execute the appropriate code.

[[synchronous-programming,synchronous-programming.title]]
=== Synchronous programming

The following code snippet shows how to wait for a {DDB} table to exist and be in an *ACTIVE* state.

[source,java]
----
DynamoDbClient dynamo = DynamoDbClient.create();
DynamoDbWaiter waiter = dynamo.waiter();

WaiterResponse<DescribeTableResponse> waiterResponse =
  waiter.waitUntilTableExists(r -> r.tableName("myTable"));

// print out the matched response with a tableStatus of ACTIVE
waiterResponse.matched().response().ifPresent(System.out::println);
----


[[asynchronous-programming,asynchronous-programming.title]]
=== Asynchronous programming

The following code snippet shows how to wait for a {DDB} table to no longer exist.

[source,java]
----
DynamoDbAsyncClient asyncDynamo = DynamoDbAsyncClient.create();
DynamoDbAsyncWaiter asyncWaiter = asyncDynamo.waiter();

CompletableFuture<WaiterResponse<DescribeTableResponse>> waiterResponse =
          asyncWaiter.waitUntilTableNotExists(r -> r.tableName("myTable"));

waiterResponse.whenComplete((r, t) -> {
  if (t == null) {
   // print out the matched ResourceNotFoundException
   r.matched().exception().ifPresent(System.out::println);
  }
}).join();
----


[[configuring-waiters,configuring-waiters.title]]
== Configuring waiters

You can customize the configuration for a waiter by using the `overrideConfiguration()` on its builder. For some operations, you can apply a custom configuration when you make the request.

[[configure-a-waiter,configure-a-waiter.title]]
=== Configure a waiter

The following code snippet shows how to override the configuration on a waiter.

[source,java]
----
// sync
DynamoDbWaiter waiter =
   DynamoDbWaiter.builder()
          .overrideConfiguration(b -> b.maxAttempts(10))
          .client(dynamoDbClient)
          .build();
// async
DynamoDbAsyncWaiter asyncWaiter =
   DynamoDbAsyncWaiter.builder()
          .client(dynamoDbAsyncClient)
          .overrideConfiguration(o -> o.backoffStrategy(
               FixedDelayBackoffStrategy.create(Duration.ofSeconds(2))))
          .scheduledExecutorService(Executors.newScheduledThreadPool(3))
          .build();
----


[[override-configuration-for-a-specific-request,override-configuration-for-a-specific-request.title]]
=== Override configuration for a specific request

The following code snippet shows how to override the configuration for a waiter on a per-request basis. Note that only some operations have customizable configurations.

[source,java]
----
waiter.waitUntilTableNotExists(b -> b.tableName("myTable"),
               o -> o.maxAttempts(10));

asyncWaiter.waitUntilTableExists(b -> b.tableName("myTable"),
                 o -> o.waitTimeout(Duration.ofMinutes(1)));
----


[[code-examples,code-examples.title]]
== Code examples

For a complete example using waiters with {DDB}, see {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-dynamodb-src-main-java-com-example-dynamodb-CreateTable-java}[CreateTable.java] in the {AWS} Code Examples Repository.

For a complete example using waiters with {S3}, see {https---github-com-awsdocs-aws-doc-sdk-examples-blob-master-javav2-example-code-s3-src-main-java-com-example-s3-S3BucketOps-java}[S3BucketOps.java] in the {AWS} Code Examples Repository.